### ISSUE TITLE
Custom book crash

### ISSUE THREAD

**Issue by tubBandit** [ricksouth/serilum-mc-mods#1036]
## **Information**
Minecraft version: 1.19-snapshot 22w15a
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer  & Multiplayer

Mod name: Starter Kit
Mod version: 3.1

could also be related to

Mod name: Collective
Mod version: 4.26

## **Description**
When trying to add a custom book with extra formatting, running /starterkit set after the book has been formatted seems to code the book wrong in the config file. This crashes the world upon first join and doesn't give you any of your items period.

I noticed in the original starterkit.txt config file that the coding is different from maybe what you have updated the collective to use? ie. the original files config looks like this...     "offhand" : "minecraft:torch-64",     vs.     this after the /starterkit set command... 
    'offhand' : '{Count:64b,id:"minecraft:torch"}',

I hope that makes sense. 

## **Crash report**
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.class_2338 net.minecraft.class_3218.method_27911()'
	at com.natamus.collective_fabric.functions.PlayerFunctions.isJoiningWorldForTheFirstTime(PlayerFunctions.java:92)
	at com.natamus.starterkit.events.FirstSpawnEvent.onSpawn(FirstSpawnEvent.java:28)
	at com.natamus.starterkit.Main.lambda$registerEvents$1(Main.java:39)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:42)
	at net.minecraft.class_3218$class_5526.handler$zfe000$invokeEntityLoadEvent(class_3218.java:1663)
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1544)
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1503)
	at net.minecraft.class_5579.method_31847(class_5579.java:217)
	at net.minecraft.class_5579.method_31820(class_5579.java:187)
	at net.minecraft.class_5579.method_31818(class_5579.java:168)
	at net.minecraft.class_3218.method_18771(class_3218.java:849)
	at net.minecraft.class_3218.method_18213(class_3218.java:835)
	at net.minecraft.class_3324.method_14570(class_3324.java:234)
	at net.minecraft.class_3248.method_33800(class_3248.java:131)
	at net.minecraft.class_3248.method_14384(class_3248.java:118)
	at net.minecraft.class_3248.redirect$zgh000$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18785(class_3248.java:68)
	at net.minecraft.class_2535.method_10754(class_2535.java:243)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:894)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:827)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:673)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ricksouth** [comment]
This should be fixed in the latest 1.19 release, this was due to an update in a snapshot. Thanks for giving the mod a try!
