### ISSUE TITLE
[FATAL] Full Bright Toggle crashes game instantly when pressing the hotkey.

### ISSUE THREAD

**Issue by KohlrabitoDev** [ricksouth/serilum-mc-mods#1108]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Forge version: N/A  OR  Fabric loader version: 0.14.7
Environment: Only tested on Multiplayer but probably singleplayer too 

Mod name: Full Bright Toggle
Mod version: fullbrightnesstoggle-fabric 1.3

## **Description**
Basically, I just press my 'G' key and the whole game crashes. Great for combat logging! Not so great for making caves light up......

## **Crash report**
Full latest.log: https://pastebin.com/MpTQdkv5

Specific crash point:
`[17:56:29] [Render thread/INFO]: Stopping worker threads
[17:56:29] [Render thread/INFO]: Started 6 worker threads
[17:56:42] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[17:56:42] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchFieldError: field_1840
	at com.natamus.fullbrightnesstoggle.events.ToggleEvent.onHotkeyPress(ToggleEvent.java:23) ~[fullbrightnesstoggle-fabric_1.19.x-1.3.jar:?]
	at com.natamus.fullbrightnesstoggle.ClientMain.lambda$onInitializeClient$0(ClientMain.java:18) ~[fullbrightnesstoggle-fabric_1.19.x-1.3.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65) ~[fabric-lifecycle-events-v1-2.0.9+21a5acaaa9-7a71574aa31cd422.jar:?]
	at net.minecraft.class_310.handler$zfo000$onEndTick(class_310.java:3890) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1869) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1101) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
[17:56:42] [Render thread/INFO]: Stopping worker threads`

**Comment by KohlrabitoDev** [comment]
Any update yet?

**Comment by ricksouth** [comment]
It took me a while to be able to fix the issue, it wasn't that easy because Mojang decided to set a maximum value for the gamma. I've done a workaround and version 2.1 of Full Brightness Toggle works again. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/full-brightness-toggle-fabric/files
