### ISSUE TITLE
Collective Crashing Game When Loading Singleplayer World

### ISSUE THREAD

**Issue by grantk00** [ricksouth/serilum-mc-mods#1176]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Fabric loader version: 0.14.8
Environment: Singleplayer 

Mod name: Collective / Double Doors / Tree Harvester
Mod version: collective-fabric-1.19.x-4.27.jar

## **Description**
I added Double Doors and Tree Harvester to a modpack I'm making and Collective came as a dependency for both, when trying to create a world the game crashed and gave this error:

```
The game crashed whilst exception ticking world
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "java.util.HashMap.get(Object)" is null
Exit Code: -1
```

Problem was fixed by removing the mod and the kind folks on reddit suggested leaving an issue here for a future fix.

## **Crash report**
```

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!
Time: 7/15/22, 2:29 PM
Description: Exception ticking world
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "java.util.HashMap.get(Object)" is null
	at com.natamus.collective_fabric.events.CollectiveEvents.onWorldTick(CollectiveEvents.java:38)
	at com.natamus.collective_fabric.CollectiveFabric.lambda$onInitialize$1(CollectiveFabric.java:27)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:84)
	at net.minecraft.class_3218.handler$bkm000$startWorldTick(class_3218.java:5723)
	at net.minecraft.class_3218.method_18765(class_3218.java:279)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Server thread
Stacktrace:
	at com.natamus.collective_fabric.events.CollectiveEvents.onWorldTick(CollectiveEvents.java:38)
	at com.natamus.collective_fabric.CollectiveFabric.lambda$onInitialize$1(CollectiveFabric.java:27)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:84)
	at net.minecraft.class_3218.handler$bkm000$startWorldTick(class_3218.java:5723)
	at net.minecraft.class_3218.method_18765(class_3218.java:279)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 0
	Level dimension: ae2:spatial_storage
	Derived: true
	Level spawn location: World: (-64,95,112), Section: (at 0,15,0 in -4,5,7; chunk contains blocks -64,0,112 to -49,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1 game time, 1 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 65957 (now: false), thunder time: 164269 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2635556048 bytes (2513 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31190.09
	Virtual memory used (MB): 20390.80
	Swap memory total (MB): 14848.00
	Swap memory used (MB): 546.67
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		ae2: Applied Energistics 2 12.0.1-alpha
		architectury: Architectury 5.9.31
		artifacts: Artifacts 7.1.1+fabric
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			com_github_llamalad7_mixinextras: MixinExtras 0.0.11
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		awesomedungeon: Awesome Dungeon 2.0.11
		awesomedungeonend: Awesome Dungeon Edition end 1.0.3
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.3
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.8
		badpackets: Bad Packets 0.1.2
		bclib: BCLib 2.0.15
		betteranimalsplus: Better Animals Plus 1.19-11.0.6
		betterend: Better End 2.0.9
		betternether: Better Nether 7.0.6
		bewitchment: Bewitchment 1.19-1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.6.0
			midnightlib: MidnightLib 0.5.2
			playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.0
		cloth-config: Cloth Config v6 7.0.73
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		java: OpenJDK 64-Bit Server VM 17
		libraryferret: Library Ferret 2.0.0
		lootr: Lootr 0.3.20.59
		minecraft: Minecraft 1.19
		modern_industrialization: Modern Industrialization 1.3.1
			magna: Magna 1.8.0-1.19
omega-config: OmegaConfig 1.0.8
			noindium: No Indium? 1.1.0+1.19
			team_reborn_energy: Energy 2.2.0
		patchouli: Patchouli 1.19-74-FABRIC
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		reborncore: Reborn Core 5.3.2
		roughlyenoughitems: Roughly Enough Items 9.1.517
		techreborn: Tech Reborn 5.3.2
		trinkets: Trinkets 3.4.0
		wthit: wthit 5.6.1
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.8-1.19
```

**Comment by shartte** [comment]
See https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6426

**Comment by ricksouth** [comment]
This has been fixed in the latest AE2 version. Thanks to the AE team for finding and fixing the problem.
