### ISSUE TITLE
Collective chokes on loading...

### ISSUE THREAD

**Issue by antiwesley** [ricksouth/serilum-mc-mods#1177]
I'll be honest, I don't even know if I _need_ collective anymore, as all my other mods are running just fine without it. 
I know I needed it at some point, but I'm unsure which mod required it. 
But still, Just letting you know... 

Thanks!

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 7/15/22, 11:57 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.0.98-universal.jar%23158!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.0.98-universal.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.98.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2376!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD collective --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/world/WorldEvent$Load
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
		at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
		at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2373!/:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2373!/:?] {}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.98.jar%23155!/:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.98.jar%23155!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.98.jar%23155!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.98.jar%23154!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: collective-1.19.0-4.28.jar
	Failure message: Collective (collective) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/world/WorldEvent$Load
	Mod Version: 4.28
	Mod Issue URL: https://github.com/ricksouth/serilum-mc-mods/labels/Library%3A%20Collective
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.world.WorldEvent$Load
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2373!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2373!/:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.98.jar%23155!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.98.jar%23155!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.98.jar%23155!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.98.jar%23154!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.18.8-xanmod1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 303102776 bytes (289 MiB) / 570425344 bytes (544 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 34181.97
	Virtual memory used (MB): 8068.75
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1.25
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SimplyTools-1.19-1.0.3.jar                        |Simply Tools                  |simplytools                   |1.19-1.0.3          |COMMON_SET|Manifest: NOSIGNATURE
		LibX-1.19-4.0.7.jar                               |LibX                          |libx                          |1.19-4.0.7          |COMMON_SET|Manifest: NOSIGNATURE
		MoreVanillaLib-1.19-4.0.1.jar                     |MoreVanillaLib                |morevanillalib                |1.19-4.0.1          |COMMON_SET|Manifest: NOSIGNATURE
		MoreVanillaTools-1.19-5.0.3.jar                   |MoreVanillaTools              |morevanillatools              |1.19-5.0.3          |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19-41.0.98-universal.jar                  |Forge                         |forge                         |41.0.98             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Aquaculture-1.19-2.4.4.jar                        |Aquaculture 2                 |aquaculture                   |1.19-2.4.4          |COMMON_SET|Manifest: NOSIGNATURE
		reap-1.19-1.0.1.jar                               |Reap Mod                      |reap                          |1.19-1.0.1          |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.11.5_Forge_1.19.jar             |Xaero's Minimap               |xaerominimap                  |22.11.5             |COMMON_SET|Manifest: NOSIGNATURE
		**collective-1.19.0-4.28.jar                        |Collective                    |collective                    |4.28                |ERROR     |Manifest: NOSIGNATURE**
		XaerosWorldMap_1.25.3_Forge_1.19.jar              |Xaero's World Map             |xaeroworldmap                 |1.25.3              |COMMON_SET|Manifest: NOSIGNATURE
		RingOfRepair-Forge-1.19.0-1.5.0.jar               |Ring of Repair                |ring_of_repair                |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		jumpoverfences-1.19-1.0.1.jar                     |Jump Over Fences              |jumpoverfences                |1.19-1.0.1          |COMMON_SET|Manifest: NOSIGNATURE
		TravelersBackpack-1.19-8.0.4.jar                  |Traveler's Backpack           |travelersbackpack             |8.0.4               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: c089d449-a6ca-414d-84eb-ff69f677c018
	FML: 41.0
	Forge: net.minecraftforge:41.0.98

**Comment by tuutaal** [comment]
I had the same... but then I went back to Forge 41.0.38 and it worked... problem is the new JEI needs to be at .98 as it addressed the changes that were made to forge. So until the rest of the mods I use update, I'll have to use the old versions of forge and sometimes the older versions of mods.

**Comment by ricksouth** [comment]
This was due to changes in Forge. If you use the latest version of Collective, it'll work. Thanks for using the mod.
