### ISSUE TITLE
Wither Skull mod drop fails to load datapacks

### ISSUE THREAD

**Issue by ItzDingus** [ricksouth/serilum-mc-mods#1199]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: 0.14.8
Environment: Multiplayer

Mod name: Always a Wither Skull (Fabric)
Mod version: [1.19.x-1.6.jar]

## **Description**
Hey! This happened..

Hello, i am using the betterMC modpack, i have added a few other mods individually, but i did isolate my issue to be specifically this mod currently, when i added this mod by itself, it fails to load my datapacks, thus stopping me from running the server.

## **Crash report**
If available.

**Comment by James103** [comment]
Can you please post the server logs from reproducing this issue?

**Comment by ItzDingus** [comment]
yes i will try and send that to you real quick

**Comment by ItzDingus** [comment]
[2022-07-25-6.log](https://github.com/ricksouth/serilum-mc-mods/files/9184224/2022-07-25-6.log)

**Comment by ItzDingus** [comment]
if you look at the bottom, about 20 lines from the bnottom you will see the datapack error, but im sure there could be more ahead further assisting you!

**Comment by ricksouth** [comment]
I'm pretty sure this is not a fault in Always a Wither Skull. There is no reference to the mod.

The following lines:
`[18:53:28] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.AssertionError: wither skelleton loot table should have LootTableSource.VANILLA
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.AssertionError: wither skelleton loot table should have LootTableSource.VANILLA
	at com.slomaxonical.architectspalette.loot.LootTableModifications.lambda$registerWitheredBones$0(LootTableModifications.java:24) ~[architects-palette-fabric-2.1.1.jar:?]
	at net.fabricmc.fabric.api.loot.v2.LootTableEvents.lambda$static$2(LootTableEvents.java:85) ~[fabric-loot-api-v2-1.1.1+03a4e568a9-e5c3b82925967e6.jar:?]
	at net.minecraft.class_60.md8850d9$lambda$apply$0$4(class_60.java:1578) ~[server-intermediary.jar:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_60.handler$bne000$apply(class_60.java:1555) ~[server-intermediary.jar:?]
	at net.minecraft.class_60.method_20712(class_60.java:59) ~[server-intermediary.jar:?]
	at net.minecraft.class_60.method_18788(class_60.java:17) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:954) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:942) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:156) ~[server-intermediary.jar:?]
	... 4 more`
	
Show a typo error in "wither skelleton loot table ". It says skelleton instead of skeleton.

Looks like "com.slomaxonical.architectspalette" -> **Architects Palette** is the problem here.

Thanks for giving the mod a try! Hope you fixed the problem.
