### ISSUE TITLE
collective fabric: mod crash on startup: zip END header not found 

### ISSUE THREAD

**Issue by drachlops** [ricksouth/serilum-mc-mods#1269]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer

Mod name: Collective (Fabric)
Mod version: 4.36

## **Description**
after trying to start mc per launcher with curseforge my game happens to crash. then the fabric loader says that a mod crashed on startup. scrolling down this error message i seem to have found the problem: it says "ZipException: zip END header not found"

## **Crash report**
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'error_notifier'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'error_notifier'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: java.lang.RuntimeException: Failed to obtain root directory for mod 'collective-fabric'!
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:148)
	at net.fabricmc.loader.impl.ModContainerImpl.getRootPaths(ModContainerImpl.java:100)
	at net.fabricmc.loader.api.ModContainer.findPath(ModContainer.java:62)
	at me.shedaniel.errornotifier.fabric.ErrorNotifierPlatformImpl.findAllErrorNotifierFiles(ErrorNotifierPlatformImpl.java:37)
	at me.shedaniel.errornotifier.ErrorNotifierPlatform.findAllErrorNotifierFiles(ErrorNotifierPlatform.java)
	at me.shedaniel.errornotifier.fabric.ErrorNotifierFileProvider.errors(ErrorNotifierFileProvider.java:25)
	at me.shedaniel.errornotifier.ErrorNotifier.lambda$init$0(ErrorNotifier.java:16)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1499)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at me.shedaniel.errornotifier.ErrorNotifier.init(ErrorNotifier.java:16)
	at me.shedaniel.errornotifier.fabric.ErrorNotifierFabric.onPreLaunch(ErrorNotifierFabric.java:11)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.io.IOException: Error accessing file:///C:/Users/sohnp/curseforge/minecraft/Instances/beest/mods/Collective-Library-Fabric-1.19.2.jar: java.util.zip.ZipException: zip END header not found
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:83)
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:59)
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPath(ModContainerImpl.java:156)
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:137)
	... 23 more
Caused by: java.util.zip.ZipException: zip END header not found
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1320)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1534)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:78)
	... 26 more

**Comment by ricksouth** [comment]
Please download mods from CurseForge, not 9minecraft or any other site. They steal mods and rehost

Use this URL: https://www.curseforge.com/minecraft/mc-mods/collective-fabric/

**Comment by ricksouth** [comment]
This is the file you'll need: https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/3919495

**Comment by ricksouth** [comment]
Let me know if the problem persists after downloading that. Make sure to also re-download any other mod you've not downloaded from CurseForge. They might contain virusses.
