### ISSUE TITLE
Hidden Recipe Book - Crash with missing keymapping

### ISSUE THREAD

**Issue by wendall911** [ricksouth/serilum-mc-mods#1294]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.3
Environment: Singleplayer

Mod name: Hidden Recipe Book
Mod version: 2.5

## **Description**
Creating a new world with default keys ... hit backspace to rename "New World", game crashes.

## **Crash report**
[11:18:27] [Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.client.KeyMapping.getKey()" because "com.natamus.hiddenrecipebook.util.Variables.hotkey" is null
	Index: 6
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplClient eventKeyboardKeyPressedEvent(Lnet/minecraftforge/client/event/ScreenEvent$KeyPressed$Pre;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$4423/0x00000008017c36d8@5f37460
		3: NORMAL
		4: ASM: org.anti_ad.mc.common.forge.CommonForgeEventHandler@893e90 onKeyPressed(Lnet/minecraftforge/client/event/ScreenEvent$KeyPressed$Pre;)V
		5: ASM: org.anti_ad.mc.ipnext.forge.ForgeEventHandler@4ed120ff onGuiKeyPressedPre(Lnet/minecraftforge/client/event/ScreenEvent$KeyPressed$Pre;)V
		6: ASM: com.natamus.hiddenrecipebook.events.BookGUIEvent@112a1e4e onKey(Lnet/minecraftforge/client/event/ScreenEvent$KeyPressed;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.KeyMapping.getKey()" because "com.natamus.hiddenrecipebook.util.Variables.hotkey" is null
	at TRANSFORMER/hiddenrecipebook@2.5/com.natamus.hiddenrecipebook.events.BookGUIEvent.onKey(BookGUIEvent.java:96)
	at TRANSFORMER/hiddenrecipebook@2.5/com.natamus.hiddenrecipebook.events.__BookGUIEvent_onKey_KeyPressed.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.1.3/net.minecraftforge.client.ForgeHooksClient.onScreenKeyPressedPre(ForgeHooksClient.java:682)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.KeyboardHandler.lambda$keyPress$4(KeyboardHandler.java:352)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:343)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:442)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:441)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.JNI.invokeV(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at TRANSFORMER/minecraft@1.19.2/com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:222)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

**Comment by wendall911** [comment]
Easy enough to work around if anyone else is having this issue. In the config disable the key binding:
allowRecipeBookToggleHotkey = false

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 3.0 of Hidden Recipe Book. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/hidden-recipe-book/files

**Comment by wendall911** [comment]
Thank you for fixing. We have been using the mod without issues with the toggle key disabled, so it hasn't been a major issue. Much appreciated!
