### ISSUE TITLE
game crashing due to collective-fabric (1.19.3)

### ISSUE THREAD

**Issue by PweSol** [ricksouth/serilum-mc-mods#1464]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.11
Environment: on startup

Mod name: collective-fabric
Mod version: 5.25

## **Description**
Game crashing on startup. Supposedly due to collective-fabric

## **Crash report**
[crash-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/10212308/crash-client.txt)

**Comment by SuryaRajgor** [comment]
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.11
Environment: on startup

Mod name: collective-fabric
Mod version: 5.45

```
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[09:27:19] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.11
[09:27:19] [ForkJoinPool-1-worker-7/WARN]: Mod net_dv8tion_jda uses the version 4.4.0_352 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0_352'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[09:27:19] [main/WARN]: Mod resolution failed
[09:27:19] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE collective-fabric 5.45 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE collective-fabric 5.45]
[09:27:19] [main/INFO]: Reason: [HARD_DEP collective-fabric 5.45 {depends fabric @ [*]}]
[09:27:19] [main/INFO]: Fix: add [add:fabric 1 ([(-?,?)])], remove [], replace []
[09:27:19] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install fabric, any version.
Unmet dependency listing:
         - Mod 'Collective (Fabric)' (collective-fabric) 5.45 requires any version of fabric, which is missing!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.11.jar:?]
```

**Comment by James103** [comment]
> Mod 'Collective (Fabric)' (collective-fabric) 5.45 requires any version of fabric, which is missing

Install the latest version of Fabric API (internally referred to as `fabric`) then restart your instance.
