### ISSUE TITLE
Collective and justplayerheads conflicting, players no longer receiving yigd graves due to internal error on death.

### ISSUE THREAD

**Issue by VirulentSlayer** [ricksouth/serilum-mc-mods#1470]
## **Information**
Minecraft version: 1.19.2
Modloader:  Fabric
Fabric loader version: 0.14.11
Environment: Multiplayer

Mod name: Collective
Mod version: collective-fabric-1.19.2-5.22

## **Description**
Upon player death, server kicks player with "Connection Lost.  Internal server error". 
The mods which are conflicting are collective and justplayerheads on latest versions.

The error is Ticking Player (see below)

[17:50:51] [Server thread/WARN]: Failed to handle packet for /192.168.50.1:63686
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.natamus.collective_fabric.functions.HeadFunctions.getPlayerHead(HeadFunctions.java:26) ~[collective-fabric-1.19.2-5.21.jar:?]
        at com.natamus.justplayerheads.events.PlayerEvent.onPlayerDeath(PlayerEvent.java:33) ~[justplayerheads-fabric_1.19.2-2.4.jar:?]
        at com.natamus.justplayerheads.Main.lambda$registerEvents$1(Main.java:31) ~[justplayerheads-fabric_1.19.2-2.4.jar:?]
        at com.natamus.collective_fabric.fabric.callbacks.CollectivePlayerEvents.lambda$static$2(CollectivePlayerEvents.java:22) ~[collective-fabric-1.19.2-5.21.jar:?]
        at net.minecraft.class_3222.handler$zef000$ServerPlayer_die(class_3222.java:9276) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_6078(class_3222.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5643(class_1309.java:1204) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5643(class_1657.java:952) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_5643(class_3222.java:713) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5670(class_1309.java:360) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5773(class_1297.java:469) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2346) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
        ... 9 more

**Comment by James103** [comment]
What other mods did you have running on the server at the time of death/kick?

**Comment by VirulentSlayer** [comment]
I beleive these are the mods running on the server,
amecs-1.3.8+mc.1.19-rc2.jar
anvilrestoration-fabric_1.19.2-1.7.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.4.62-fabric.jar
areas-fabric_1.19.2-3.2.jar
bedspreads-fabric-6.0.0+1.19.2.jar
BetterAdvancements-Fabric-1.19.2-0.2.2.142.jar
boatcontainer-1.2.4-1.19.jar
cloth-config-8.2.88-fabric.jar
collective-fabric-1.19.2-5.22.jar
comforts-fabric-6.0.3+1.19.2.jar
compacthelpcommand-fabric_1.19.2-1.7.jar
conduitspreventdrowned-fabric_1.19.2-2.0.jar
Controlling-fabric-1.19.2-10.0+7.jar
CreativeCore_FABRIC_v2.9.3_mc1.19.2.jar
cryingportals-fabric_1.19.2-1.8.jar
cyclepaintings-fabric_1.19.2-2.8.jar
easyelytratakeoff-fabric_1.19.2-3.2.jar
edibles-fabric_1.19.2-3.0.jar
entityculling-fabric-1.5.2-mc1.19.jar
fabric_1.19.2-3.0.jar
extendedbonemeal-fabric_1.19.2-2.1.jar
fabric-api-0.69.0+1.19.2.jar
FpsReducer2-fabric-1.19.2-2.1.jar
grassseeds-fabric_1.19.2-2.3.jar
grindstonesharpertools-fabric_1.19.2-2.3.jar
handoveryouritems-fabric_1.19.2-2.1.jar
healingcampfire-fabric_1.19.2-4.0.jar
immersive-portals-2.2.5-mc1.19.2-fabric.jar
infinitetrading-fabric_1.19.2-3.1.jar
iris-mc1.19.2-1.4.5.jar
journeymap-1.19.2-5.9.0beta4-fabric.jar
justmobheads-fabric_1.19.2-6.2.jar
lithium-fabric-mc1.19.2-0.10.4.jar
minimotd-fabric-mc1.19.2-2.0.9.jar
modmenu-4.1.2.jar
mousewheelie-1.10.4+mc1.19.2.jar
naturallychargedcreepers-fabric_1.19.2-2.4.jar
NaturesCompass-1.19.2-2.1.0-fabric.jar
Patchouli-1.19.2-77-FABRIC.jar
petnames-fabric_1.19.2-2.3.jar
rainbegoneritual-fabric_1.19.2-2.4.jar
randombonemealflowers-fabric_1.19.2-3.3.jar
recast-fabric_1.19.2-2.2.jar
RoughlyEnoughItems-9.1.580.jar
scaffoldingdropsnearby-fabric_1.19.2-2.2.jar
simple-hud-utilities-2.5.2.jar
SimpleBackpack_Fabric-1.19.2-1.3.25.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
softerhaybales-fabric_1.19.2-2.2.jar
starlight-1.1.1+fabric.ae22326.jar
textile_backup-2.4.0-1.19.1.jar
tntbreaksbedrock-fabric_1.19.2-2.5.jar
variantcomposters-1.0.7.jar
villagebellrecipe-fabric_1.19.2-2.0.jar
voicechat-fabric-1.19.2-2.3.23.jar
wooltweaks-fabric_1.19.2-2.4.jar
xp_obelisk-0.4.7-r+1.19.2-Fabric.jar
youre-in-grave-danger-1.4.6.jar

**Comment by ricksouth** [comment]
Does this still happen? I assume it had something to do with the API being down, giving a strange output which the mod didn't expect. But when trying it in my dev environment, it just works.

**Comment by VirulentSlayer** [comment]
Things seem good again now. additional info posted here: https://github.com/ricksouth/serilum-mc-mods/issues/1473

**Comment by ricksouth** [comment]
I believe it was due to the API being down, which the mod did not like. Thanks for opening the issue and giving the mod a try! Everything should work again as normal, but just in case I've uploaded version 5.35 of Collective to prevent errors in the future. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
