### ISSUE TITLE
Nether portal spread crashing on 1.19.2 pulling null error?

### ISSUE THREAD

**Issue by zakman9797** [ricksouth/serilum-mc-mods#1537]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.3
Environment: On Startup.

Mod name: Nether Portal Spread
Mod version: 7.0 Latest

It crashed.

-- MOD netherportalspread --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.3.jar%23821!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.3.jar%23820!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /E:/Minecraft/Instances/1192/mods/netherportalspread-1.19.2-7.0.jar
	Failure message: Nether Portal Spread (netherportalspread) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 7.0
	Mod Issue URL: https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Nether%20Portal%20Spread
	Exception message: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: "minecraft:coal_block"

[crash-2023-01-10_19.35.32-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/10387818/crash-2023-01-10_19.35.32-fml.txt)

Full log attached at bottom.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.1 of Nether Portal Spread. Appreciate it.

https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread/files
