### ISSUE TITLE
Villager Death Messages - Server crash

### ISSUE THREAD

**Issue by sternschnaube** [ricksouth/serilum-mc-mods#1573]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.13

Mod name: Villager Death Messages
Mod version: 3.0

Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:890) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:283) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:830) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zji000$modifiedRunLoop(MinecraftServer:5908) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:655) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:264) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.AbstractMethodError: Receiver class com.natamus.villagerdeathmessages.ModFabric$$Lambda$5338/0x0000000801b95e08 does not define or inherit an implementation of the resolved method 'abstract boolean onDeath(net.minecraft.class_1937, net.minecraft.class_1297, net.minecraft.class_1282)' of interface com.natamus.collective.fabric.callbacks.CollectiveEntityEvents$Living_Entity_Death.
	at com.natamus.collective.fabric.callbacks.CollectiveEntityEvents.lambda$static$2(CollectiveEntityEvents.java:21) ~[collective-1.19.3-6.43.jar:?]
	at net.minecraft.entity.LivingEntity.handler$cgp000$LivingEntity_die(LivingEntity:30141) ~[?:?]
	at net.minecraft.entity.LivingEntity.onDeath(LivingEntity) ~[?:?]
	at net.minecraft.entity.LivingEntity.damage(LivingEntity:1210) ~[?:?]
	at net.minecraft.entity.passive.SquidEntity.damage(SquidEntity:183) ~[?:?]
	at net.minecraft.entity.passive.GlowSquidEntity.damage(GlowSquidEntity:83) ~[?:?]
	at net.minecraft.entity.mob.WaterCreatureEntity.tickWaterBreathingAir(WaterCreatureEntity:56) ~[?:?]
	at net.minecraft.entity.mob.WaterCreatureEntity.baseTick(WaterCreatureEntity:67) ~[?:?]
	at net.minecraft.entity.Entity.tick(Entity:467) ~[?:?]
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2365) ~[?:?]
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:352) ~[?:?]
	at net.minecraft.server.world.ServerWorld.track(ServerWorld:26235) ~[?:?]
	at net.minecraft.server.world.ServerWorld.redirect$ehl000$onTickNonPassenger(ServerWorld:26251) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:728) ~[?:?]
	at net.minecraft.world.World.tickEntity(World:482) ~[?:?]
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:374) ~[?:?]
	at net.minecraft.world.EntityList.forEach(EntityList:54) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:342) ~[?:?]
	at net.minecraft.server.MinecraftServer.redirect$beh000$onTickingWorld(MinecraftServer:7309) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:886) ~[server-intermediary.jar:?]
	... 6 more

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 3.1 of Villager Death Messages. Appreciate it.

https://www.curseforge.com/minecraft/mc-mods/villager-death-messages/files

**Comment by venaminecraft** [comment]
Thanks 😊
