### ISSUE TITLE
Crashed whilst Ticking Player

### ISSUE THREAD

**Issue by Cupidodger** [ricksouth/serilum-mc-mods#1756]
## **Information**
Minecraft version: 1.19.23
Modloader: Forge
Forge version: 44.1.23
Environment: Singleplayer

Mod name: Just-Player-Head-Mod-Forge-1.19.3
Mod version: 1.19.3

## **Description**
crashed whilst Ticking player error upon every death. checked all my mods and the error ended when I took this mod off. not only did the game crash but all entities were deleted so all my items were gone

## **Crash report**---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-05-09 01:10:18
Description: Ticking player

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.natamus.collective.functions.HeadFunctions.getPlayerHead(HeadFunctions.java:24) ~[Collective-Library-Forge-1.19.3.jar%23166!/:5.25] {re:classloading}
	at com.natamus.justplayerheads.events.PlayerEvent.entityDeath(PlayerEvent.java:57) ~[Just-Player-Head-Mod-Forge-1.19.3.jar%23168!/:1.0] {re:classloading}
	at com.natamus.justplayerheads.events.__PlayerEvent_entityDeath_LivingDeathEvent.invoke(.dynamic) ~[Just-Player-Head-Mod-Forge-1.19.3.jar%23168!/:1.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2386!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:305) ~[forge-1.19.3-44.1.23-universal.jar%23175!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_6667_(ServerPlayer.java:568) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:mixins.essential.json:feature.particles.Mixin_PreserveRealYawDuringInventoryRendering,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_6469_(Player.java:849) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:entity.player.EntityPlayerAccessor,pl:mixin:APP:mixins.essential.json:entity.player.MixinEntityPlayer,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:686) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:362) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:mixins.essential.json:feature.particles.Mixin_PreserveRealYawDuringInventoryRendering,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:417) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:block.hopper.EntityAccessor,pl:mixin:APP:canary.mixins.json:entity.collisions.movement.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.suffocation.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2266) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:mixins.essential.json:feature.particles.Mixin_PreserveRealYawDuringInventoryRendering,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:237) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:entity.player.EntityPlayerAccessor,pl:mixin:APP:mixins.essential.json:entity.player.MixinEntityPlayer,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:462) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:259) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.essential.json:feature.ice.client.Mixin_NettyIceClient,pl:mixin:APP:mixins.essential.json:feature.ice.common.Mixin_IceChannelIsNotLocal,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.essential.json:feature.ice.server.Mixin_NettyIceServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:890) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:816) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:85) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.essential.json:server.integrated.MixinIntegratedServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.natamus.collective.functions.HeadFunctions.getPlayerHead(HeadFunctions.java:24) ~[Collective-Library-Forge-1.19.3.jar%23166!/:5.25] {re:classloading}
	at com.natamus.justplayerheads.events.PlayerEvent.entityDeath(PlayerEvent.java:57) ~[Just-Player-Head-Mod-Forge-1.19.3.jar%23168!/:1.0] {re:classloading}
	at com.natamus.justplayerheads.events.__PlayerEvent_entityDeath_LivingDeathEvent.invoke(.dynamic) ~[Just-Player-Head-Mod-Forge-1.19.3.jar%23168!/:1.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2386!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:305) ~[forge-1.19.3-44.1.23-universal.jar%23175!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_6667_(ServerPlayer.java:568) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:mixins.essential.json:feature.particles.Mixin_PreserveRealYawDuringInventoryRendering,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_6469_(Player.java:849) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:entity.player.EntityPlayerAccessor,pl:mixin:APP:mixins.essential.json:entity.player.MixinEntityPlayer,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:686) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:362) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:mixins.essential.json:feature.particles.Mixin_PreserveRealYawDuringInventoryRendering,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:417) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:block.hopper.EntityAccessor,pl:mixin:APP:canary.mixins.json:entity.collisions.movement.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.suffocation.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2266) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:mixins.essential.json:feature.particles.Mixin_PreserveRealYawDuringInventoryRendering,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:237) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:entity.player.EntityPlayerAccessor,pl:mixin:APP:mixins.essential.json:entity.player.MixinEntityPlayer,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 219
	Entity Name: Cupidodger
	Entity's Exact location: 83.69, 59.59, 105.47
	Entity's Block location: World: (83,59,105), Section: (at 3,11,9 in 5,3,6; chunk contains blocks 80,-64,96 to 95,319,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.02, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:462) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:259) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.essential.json:feature.ice.client.Mixin_NettyIceClient,pl:mixin:APP:mixins.essential.json:feature.ice.common.Mixin_IceChannelIsNotLocal,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.essential.json:feature.ice.server.Mixin_NettyIceServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:890) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:816) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:85) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.essential.json:server.integrated.MixinIntegratedServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.19.3-20221207.122022-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:feature.sps.Mixin_IntegratedServerResourcePack,pl:mixin:APP:mixins.essential.json:server.MinecraftServerMixin_PvPGameRule,pl:mixin:APP:mixins.essential.json:server.Mixin_PublishServerStatusResponse,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1120669840 bytes (1068 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.89
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 6600
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: DriverVersion=30.0.14023.3004
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20885.60
	Virtual memory used (MB): 15874.04
	Swap memory total (MB): 4608.00
	Swap memory used (MB): 67.79
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Cupidodger'/219, l='ServerLevel[Its time to Party]', x=83.69, y=59.59, z=105.47]]
	Data Packs: vanilla, mod:justmobheads, mod:forge, mod:justplayerheads, mod:collective, mod:essential (incompatible), mod:canary, mod:spark (incompatible), mod:betterfpsdist (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.19.3-forge-44.1.23
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar essential-loader TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		kotlinforforge@3.6.0
		javafml@null
	Mod List: 
		client-1.19.3-20221207.122022-srg.jar             |Minecraft                     |minecraft                     |1.19.3              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Canary-Mod-Forge-1.19.3.jar                       |Canary                        |canary                        |0.1.9               |DONE      |Manifest: NOSIGNATURE
		Just-Mob-Heads-Mod-Forge-1.19.3.jar               |Just Mob Heads                |justmobheads                  |6.2                 |DONE      |Manifest: NOSIGNATURE
		Spark-Mod-Forge-1.19.3.jar                        |spark                         |spark                         |1.10.29             |DONE      |Manifest: NOSIGNATURE
		Better-Fps-Mod-Forge-1.19.4.jar                   |betterfpsdist mod             |betterfpsdist                 |1.19.4-2.8          |DONE      |Manifest: NOSIGNATURE
		forge-1.19.3-44.1.23-universal.jar                |Forge                         |forge                         |44.1.23             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Just-Player-Head-Mod-Forge-1.19.3.jar             |Just Player Heads             |justplayerheads               |2.2                 |DONE      |Manifest: NOSIGNATURE
		Collective-Library-Forge-1.19.3.jar               |Collective                    |collective                    |5.25                |DONE      |Manifest: NOSIGNATURE
		Essential (forge_1.19.3).jar                      |Essential                     |essential                     |12266+deploy-staging|DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: cdaa3dd7-e03e-4cca-bc85-c04b274d3e0b
	FML: 44.1
	Forge: net.minecraftforge:44.1.23

**Comment by ricksouth** [comment]
Where do you download mods from? Which website?

**Comment by Cupidodger** [comment]
9minecraft.net

**Comment by James103** [comment]
Please redownload all your mods from CurseForge or Modrinth.
