### ISSUE TITLE
Crash(incompatibility between farmer's respite and tree harvester)

### ISSUE THREAD

**Issue by Lunatikis** [ricksouth/serilum-mc-mods#1769]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge 
Forge version: 40.2.0 
Environment: Multiplayer

Mod name: Mod
Mod version: 1.18.2-8.0

## **Description**
The server  crashes when i enter nether. It seems server crashes because there is conflict between tree harvester mod and farmers respite mod.

## **Crash report**
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[0, 1, 2]} to 3 on Block{farmersrespite:coffee_stem_middle}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:125) ~[server-1.18.2-20220404.173914-srg.jar%23283!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fluidlogged.forge.mixins.json:accessor.StateAccessor,pl:mixin:APP:canary.mixins.json:alloc.blockstate.StateHolderMixin,pl:mixin:A}
	at com.farmersrespite.common.block.CoffeeMiddleStemBlock.m_7719_(CoffeeMiddleStemBlock.java:131) ~[FarmersRespite-1.18.2-1.3.0.jar%23137!/:1.18.2-1.0.4] {re:classloading}
	at com.farmersrespite.common.block.CoffeeMiddleStemBlock.m_7455_(CoffeeMiddleStemBlock.java:94) ~[FarmersRespite-1.18.2-1.3.0.jar%23137!/:1.18.2-1.0.4] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60735_(BlockBehaviour.java:681) ~[server-1.18.2-20220404.173914-srg.jar%23283!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:snowrealmagic.mixins.json:BlockStateMixin,pl:mixin:APP:canary.mixins.json:ai.pathing.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:block.flatten_states.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:chunk.block_counting.BlockStateBaseMixin,pl:mixin:APP:fluidlogged.forge.mixins.json:AbstractBlockStateMixin,pl:mixin:A}
	at com.natamus.treeharvester_common_forge.events.LeafEvents.onWorldTick(LeafEvents.java:52) ~[treeharvester-1.18.2-8.0.jar%23260!/:?] {re:classloading}
	at com.natamus.treeharvester.forge.events.ForgeLeafEvents.onWorldTick(ForgeLeafEvents.java:21) ~[treeharvester-1.18.2-8.0.jar%23260!/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_907_ForgeLeafEvents_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreWorldTick(ForgeEventFactory.java:895) ~[forge-1.18.2-40.2.0-universal.jar%23288!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[server-1.18.2-20220404.173914-srg.jar%23283!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23283!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23283!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23283!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23283!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.1 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester
