### ISSUE TITLE
Tree Harvester interaction with Farmer's Respite

### ISSUE THREAD

**Issue by TheMikeHuisman** [ricksouth/serilum-mc-mods#1794]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Forge version: Fabric loader version: 0.14.21
Environment: Multiplayer

First mod name: Tree Harvester
First mod version: 2.3.8

Second mod name: Farmer's Respite
Second mod version: 2.2.4

## **Description**
It seems like a player on our server picked up or loaded an item from the Farmer's Respite mod and the Tree Harvester mod isn't sure what to do with it.

## **Crash report**
java.lang.IllegalArgumentException: Cannot set property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2]} to 3 on Blo>
        at net.minecraft.class_2688.method_11657(class_2688.java:125)
        at com.chefsdelights.farmersrespite.common.block.CoffeeStemBlock.method_9652(CoffeeStemBlock.java:112)
        at com.chefsdelights.farmersrespite.common.block.CoffeeStemBlock.method_9514(CoffeeStemBlock.java:76)
        at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:948)
        at com.natamus.treeharvester_common_fabric.events.LeafEvents.onWorldTick(LeafEvents.java:52)
        at com.natamus.treeharvester.ModFabric.lambda$loadEvents$1(ModFabric.java:46)
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:84)
        at net.minecraft.class_3218.handler$bgm000$fabric-lifecycle-events-v1$startWorldTick(class_3218.java:6224)
        at net.minecraft.class_3218.method_18765(class_3218.java:280)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
        at net.minecraft.class_3176.method_3813(class_3176.java:289)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.base/java.lang.Thread.run(Thread.java:1589)

[crash-2023-06-02_22.48.12-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11641838/crash-2023-06-02_22.48.12-server.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.1 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester
