### ISSUE TITLE
Tree Harvester crash in 1.20

### ISSUE THREAD

**Issue by willydee** [ricksouth/serilum-mc-mods#1802]
Harvesting a tree crashes the game. Seems not to be related to other mods; all but required ones have been disabled.

```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2023-06-08 23:04:59
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_3614
	at com.natamus.treeharvester_common_fabric.processing.LeafProcessing.<clinit>(LeafProcessing.java:100)
	at com.natamus.treeharvester_common_fabric.events.TreeCutEvents.onTreeHarvest(TreeCutEvents.java:130)
	at com.natamus.treeharvester.ModFabric.lambda$loadEvents$4(ModFabric.java:59)
	at net.fabricmc.fabric.api.event.player.PlayerBlockBreakEvents.lambda$static$0(PlayerBlockBreakEvents.java:44)
	at net.minecraft.class_3225.handler$zek000$fabric-events-interaction-v0$breakBlock(class_3225.java:609)
	at net.minecraft.class_3225.method_14266(class_3225.java:255)
	at net.minecraft.class_3225.method_21717(class_3225.java:228)
	at net.minecraft.class_3225.method_14263(class_3225.java:203)
	at net.minecraft.class_3244.method_12066(class_3244.java:1083)
	at net.minecraft.class_2846.method_12361(class_2846.java:42)
	at net.minecraft.class_2846.method_11054(class_2846.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3614
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Linux (amd64) version 6.3.6-arch1-1
	Java Version: 20, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1649371536 bytes (1572 MiB) / 2764046336 bytes (2636 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 50789.21
	Virtual memory used (MB): 7904.12
	Swap memory total (MB): 42816.69
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms1024m -Xmx8192m
	Fabric Mods: 
		collective: Collective 6.57
		fabric-api: Fabric API 0.83.0+1.20
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c927
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b27
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d127
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b27
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b27
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f27
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b27
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b327
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b327
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b27
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b27
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe27
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.10+b3afc78b27
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b27
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b27
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b27
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b327
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a27
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b27
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b27
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da27
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b327
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b27
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b27
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c627
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b27
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b27
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b27
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b27
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b327
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b27
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b27
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b27
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b27
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b27
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b27
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b327
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b327
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b27
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.4+b3afc78b27
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b27
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b27
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b27
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b27
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b27
		fabricloader: Fabric Loader 0.14.21
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 20
		minecraft: Minecraft 1.20
		sodium: Sodium 0.4.10+build.27
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a27
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b27
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b27
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d27
		treeharvester: Tree Harvester 8.1
	Loaded Shaderpack: ComplementaryShaders_v4.7.2.zip
		Profile: HIGH (+0 options changed by user)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['BigWhale684107'/163, l='ServerLevel[First Steps]', x=29.57, y=63.00, z=-268.73]]
	Data Packs: vanilla, fabric, file/Terralith_1.20_v2.4.0.zip, bundle
	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by ricksouth** [comment]
Thanks for opening the issue. Are you in single or multiplayer? Which tree are you cutting down?

**Comment by willydee** [comment]
Singleplayer. Tried an oak and an acacia, happens every time. I'll try to reproduce on a vanilla instance w/o any shaders or such.

**Comment by ricksouth** [comment]
I can't seem to replicate it in my dev environment. Will try the exported jar file as well. Seems to be related to me using the new MapColor, *might* be something wrong in Fabric though more likely something on my end

**Comment by ricksouth** [comment]
Hmm, fresh install of Fabric with Collective & Tree Harvester also doesn't seem to cause any issues on 1.20

**Comment by willydee** [comment]
I cannot reproduce the crash in a vanilla+fabric environment, so it's probably interference with something else I have added to the previous instance. Although all other mods had been disabled, there are still shaders and data packs involved.

**Comment by ricksouth** [comment]
Could you try to add them one by one, so we can open an issue with the other author involved?

**Comment by willydee** [comment]
Working on it.

**Comment by ricksouth** [comment]
This is the line of code where the game is having issues:
https://github.com/ricksouth/serilum-mc-mod-sources/blob/main/sources/Tree%20Harvester/1.20.0/Common/src/main/java/com/natamus/treeharvester/processing/LeafProcessing.java#L116

**Comment by willydee** [comment]
Tested so far, no crash:
~~Iris/Sodium~~
~~Terralith data pack~~
~~Complementary shaders~~
~~BlueNerd VPlus texture pack~~
~~Experimental bundle~~

**Comment by willydee** [comment]
Created a new world in the same instance, with nothing modified except adding TreeHarvester: *Crash*. So it must be something that has already somehow damaged the instance. In another instance, I'm not able to reproduce this. :frowning_face:

**Comment by willydee** [comment]
I'd suggest to close the issue for now; I'll get back to you in case I can narrow down the cause.

**Comment by ricksouth** [comment]
Could you upload the world here as a zip that caused the crash? Thanks for the research nonetheless!

**Comment by willydee** [comment]
[New_World.zip](https://github.com/ricksouth/serilum-mc-mods/files/11693336/New_World.zip)

But as suggested, it might be the instance causing the fault, not the world.
