### ISSUE TITLE
The game breaks if you don't write the size of the area

### ISSUE THREAD

**Issue by Laiksion** [ricksouth/serilum-mc-mods#1806]
## **Information**
Minecraft version: 1.20.0
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Multiplayer [It also happens in singleplayer]

Mod name: Areas
Mod version: 1.20-4.4 and 1.20-4.3 and 1.20.1-4.4

## **Description**
If you write in a sign:
Line1: [Area]
Line2: ExampleName
"The error occurs when after [Area] you do not specify the size of the area"

![AreasErrorReplication](https://github.com/ricksouth/serilum-mc-mods/assets/74372467/20f649cb-14c5-43af-a125-4388a7c82a4b)

## **Crash report**
[23:51:33] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at net.minecraft.class_8242.method_49858(class_8242.java:105) ~[server-intermediary.jar:?]
	at net.minecraft.class_8242.method_49857(class_8242.java:99) ~[server-intermediary.jar:?]
	at com.natamus.areas_common_fabric.util.Util.getAreaSign(Util.java:152) ~[areas-1.20.0-4.3.jar:?]
	at com.natamus.areas_common_fabric.events.AreaEvent.onPlayerTick(AreaEvent.java:84) ~[areas-1.20.0-4.3.jar:?]
	at com.natamus.areas.ModFabric.lambda$loadEvents$1(ModFabric.java:35) ~[areas-1.20.0-4.3.jar:?]
	at com.natamus.collective.fabric.callbacks.CollectivePlayerEvents.lambda$static$0(CollectivePlayerEvents.java:19) ~[collective-1.20.0-6.57.jar:?]
	at net.minecraft.class_3222.handler$zgl000$collective$ServerPlayer_tick(class_3222.java:7848) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_5773(class_3222.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 5 more

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features.

https://www.curseforge.com/minecraft/mc-mods/areas/files
