### ISSUE TITLE
Crashing out on load

### ISSUE THREAD

**Issue by Stixz** [ricksouth/serilum-mc-mods#1869]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.1.1
Environment: Singleplayer

Mod name: Realistic Bees
Mod version: 3.4

## **Description**
Only mod enabled and MC/Forge still crashes on loading.

## **Crash report**
[Prism Launcher version 7.1.txt](https://github.com/ricksouth/serilum-mc-mods/files/12014236/Prism.Launcher.version.7.1.txt)

Thanks!

**Comment by EightBitBBQ** [comment]
I opend your log with Notepad++
On line 192 it says its missing Collective 6.57
You can download the version here:
https://www.curseforge.com/minecraft/mc-mods/collective

**Comment by JynRey** [comment]
Hi, 
I'm having the same issue since I updated the Collective to version 6.63 via the curse launcher (using Fabric mod loader) today. It's fine when I disable it but the moment I re-enable it the game crashes before it even launches. 
It even happens when I have disabled all mods aside from Cloth Config and all the Serilum mods I have installed. I have even tried disabling each mod in turn and running it with just it and Cloth Config and I get the same report each time. 

Its odd as I cant see anything that suggest this is the issue in the Uncaught exception in thread (see below, I'm not sure how to read it but someone might be able to tell me what is going on) but I think Cloth was also updated at the same time but it is only when these mods are also enable that I get the crash, it doesn't happen with any other mods.

Do I just need to revert back to an older version of Collective?

Uncaught exception in thread "main"
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [collective.mixins.json:TitleScreenMixin from mod collective] from phase [DEFAULT] in config [collective.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'com.natamus.collective.mixin.TitleScreenMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:865)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 13 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'com.natamus.collective.mixin.TitleScreenMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1314)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:858)
	... 16 more

**Comment by ricksouth** [comment]
Appreciate you opening the issue! Something has gone wrong with the update I just exported. Looking into it now!

**Comment by ricksouth** [comment]
@Stixz Please install Collective to fix the issue.

@JynRey Thanks for the comment! This is something gone wrong with the export on my end. Working on it now!

**Comment by ricksouth** [comment]
It is a little more work than I thought. Archived the new versions for now. Please use version 6.62 to fix it for the time being

**Comment by cootshk** [comment]
Also happens on fabric (modrinth launcher)
https://mclo.gs/7H4XTwC

**Comment by GuyInUniverse** [comment]
Currently getting a crash on startup as well with the new Collective version on Modrinth. I'm playing on 1.20.1 using Fabric. Here's the log if it helps!
https://mclo.gs/Ilo2FjC

**Comment by Czompi** [comment]
Hello!
I've updated to Collective version 6.64 and got a similar (mixin-related) crash on 1.19.2  and 1.20.1, that JynRey got.
Log:
```log
[11:13:10] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config collective.mixins.json for mod collective
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config collective.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93) ~[fabric-loader-0.14.21.jar:?]
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'collective.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93) ~[fabric-loader-0.14.21.jar:?]
	... 3 more

```

**Comment by ricksouth** [comment]
I've just uploaded Collective version 6.65, which should fix the issues. Please let me know if the problem persists, due to how I merge Forge and Fabric it was a bit difficult to find.

**Comment by Czompi** [comment]
It works correctly with 6.65 on 1.19.2 and 1.20.1. Thank you for the quick fix.
