### ISSUE TITLE
Collective Fabric 1.20.1 fails to load

### ISSUE THREAD

**Issue by DemonSeedxp** [ricksouth/serilum-mc-mods#1872]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Singleplayer

Mod name: Collective
Mod version: 1.20.1-6.64

## **Description**
`Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config collective.mixins.json for mod collective
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config collective.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'collective.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more
`

## **Crash report**

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/12026745/latest.log)

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! I've uploaded Collective version 6.65 a few minutes ago, this should fix the issue. Could you confirm that?

**Comment by DemonSeedxp** [comment]
sure will one min and i'll let you know

**Comment by DemonSeedxp** [comment]
prefect! that was some timely service too, thanks for fixing me up

**Comment by Sunconure11** [comment]
Encountering something similar on 1.19.2 too.

https://gist.github.com/Sunconure11/36e10822c1ba5c7e5c369c09d0ddb66c

**Comment by ricksouth** [comment]
> Encountering something similar on 1.19.2 too.
> 
> https://gist.github.com/Sunconure11/36e10822c1ba5c7e5c369c09d0ddb66c

Please update Collective to version 6.65

**Comment by Sunconure11** [comment]
I didn't see the update until I responded to this issue.
