### ISSUE TITLE
Collective & Passive Shield Installed. 

### ISSUE THREAD

**Issue by Roaring1** [ricksouth/serilum-mc-mods#1938]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge 
Forge version: 36.2.33
Environment: Singleplayer

Mod name: Collective OR Passive Shield (idk what one)
Mod version:  Collective - latest - "collective-1.16.5-5.49.jar"; Passive Shield - latest - "passiveshield_1.16.5-2.6.jar"

## **Description**
The game wouldn't start (I went through 150 mods by hand, sorting through them until I found this one). 
-Eventually, I found the error being one of the two, Collective or Passive shield. The game version is 1.16.5. Forge, via the curseforge launcher. 
-I'm not actually caring to solve this issue personally, this is just a warning for the developer, like the mod author, or those who come across it. I'm just gonna disable the mod entirely until then.

## **Crash report**
----- Here's one that's close, most of them are like this: 

[00:09:39] [main/INFO]: ModLauncher running: args [--username, Roaring4, --version, forge-36.2.33, --gameDir, C:\Users\roari\curseforge\minecraft\Instances\HighRez (1), --assetsDir, C:\Users\roari\curseforge\minecraft\Install\assets, --assetIndex, 1.16, --uuid, 26027309cb304e9891176312c3b0a12c, --accessToken, ????????, --userType, msa, --versionType, release, --width, 2560, --height, 1440, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.33, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[00:09:39] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_51 by Oracle Corporation
[00:09:39] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[00:09:39] [main/INFO]: OptiFineTransformationService.onLoad
[00:09:39] [main/INFO]: OptiFine ZIP file: C:\Users\roari\curseforge\minecraft\Instances\HighRez (1)\mods\OptiFine_1.16.5_HD_U_G8.jar
[00:09:39] [main/INFO]: Target.PRE_CLASS is available
[00:09:39] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[00:09:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/roari/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[00:09:39] [main/INFO]: OptiFineTransformationService.initialize
[00:09:40] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[00:09:40] [main/INFO]: OptiFineTransformationService.transformers
[00:09:40] [main/INFO]: Targets: 311
[00:09:40] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[00:09:40] [main/ERROR]: Mixin config notenoughcrashes.mixins.json does not specify "minVersion" property
[00:09:40] [main/ERROR]: Mixin config notenoughcrashes.forge.mixins.json does not specify "minVersion" property
[00:09:40] [main/ERROR]: Mixin config spoornextras.mixins.json does not specify "minVersion" property
[00:09:40] [main/ERROR]: Mixin config better_loading_screen-common.mixins.json does not specify "minVersion" property
[00:09:40] [main/ERROR]: Mixin config better_loading_screen.mixins.json does not specify "minVersion" property
[00:09:40] [main/ERROR]: Mixin config noaddrepcost.mixin.json does not specify "minVersion" property
[00:09:40] [main/INFO]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[00:09:40] [main/INFO]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[00:09:40] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-36.2.33, --gameDir, C:\Users\roari\curseforge\minecraft\Instances\HighRez (1), --assetsDir, C:\Users\roari\curseforge\minecraft\Install\assets, --uuid, 26027309cb304e9891176312c3b0a44c, --username, Roaring4, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release, --width, 2560, --height, 1440]
[00:09:40] [main/INFO]: Loaded configuration file for Rubidium: 30 options available, 0 override(s) found
[00:09:40] [main/WARN]: Reference map 'findme.refmap.json' for findme.mixins.json could not be read. If this is a development environment you can ignore this message
[00:09:40] [main/INFO]: Loaded configuration file for Rubidium: 30 options available, 0 override(s) found
[00:09:41] [main/WARN]: Reference map 'mixins.noaddrepcost.refmap.json' for noaddrepcost.mixin.json could not be read. If this is a development environment you can ignore this message
[00:09:41] [main/INFO]: Loaded rule configuration file for RoadRunner: 81 options available, 0 override(s) found
[00:09:41] [main/INFO]: Transforming class: net.minecraft.entity.Entity
[00:09:41] [main/INFO]: Transforming class: net.minecraft.tileentity.TileEntity
[00:09:41] [main/INFO]: APPLYING MIXIN: de.keksuccino.auudio.mixin.client.MixinAudioStreamManager | TO TARGET: net.minecraft.client.audio.AudioStreamManager
[00:09:41] [main/INFO]: APPLYING MIXIN: de.keksuccino.auudio.mixin.client.MixinSoundEngine | TO TARGET: net.minecraft.client.audio.SoundEngine
[00:09:41] [main/INFO]: Transforming method: cubeInFrustum net.minecraft.client.renderer.culling.ClippingHelper
[00:09:41] [main/INFO]: Patching LivingEntity#attackEntityFrom
[00:09:41] [main/INFO]: Transforming method: setupTerrain net.minecraft.client.renderer.WorldRenderer
[00:09:41] [main/INFO]: Transforming method: updateCameraAndRender net.minecraft.client.renderer.WorldRenderer
[00:09:41] [main/INFO]: Patching LivingEntity#attackEntityFrom
[00:09:41] [main/INFO]: Transforming class: net.minecraft.tileentity.TileEntity
[00:09:41] [main/WARN]: Error loading class: com/terraforged/mod/chunk/generator/FeatureGenerator (java.lang.ClassNotFoundException: null)
[00:09:41] [main/WARN]: @Mixin target com.terraforged.mod.chunk.generator.FeatureGenerator was not found lod.mixins.json:MixinTFChunkGenerator
[00:09:41] [main/INFO]: Patching ModelBakery#<init>
[00:09:41] [main/INFO]: Patching ItemStack#onItemUse
[00:09:41] [main/INFO]: Patching DataPackRegistries#<init>
[00:09:42] [Thread-4/INFO]: Completed deep scan of NekosEnchantedBooks-1.16-1.7.0.jar
[00:09:42] [Thread-4/INFO]: Completed deep scan of BetterModsButton-v1.0.5-1.16.5-Forge.jar
[00:09:42] [Thread-4/INFO]: Completed deep scan of SimpleDiscordRichPresence-1.4.0-build.3+mc1.16.5.jar
[00:09:42] [Thread-4/INFO]: Completed deep scan of BetterMineshafts-Forge-1.16.4-2.0.4.jar
[00:09:42] [Thread-4/INFO]: Completed deep scan of CodeChickenLib-1.16.5-4.0.7.445-universal.jar
[00:09:42] [Thread-4/INFO]: Completed deep scan of xptome-1.16.5-v2.1.5.jar
[00:09:42] [Thread-4/INFO]: Completed deep scan of createaddition-1.16.5-20220129a.jar
[00:09:42] [Thread-4/INFO]: Completed deep scan of CosmeticArmorReworked-1.16.5-v5.jar
[00:09:42] [Thread-4/INFO]: Completed deep scan of expandability-2.0.1-forge.jar
[00:09:42] [Thread-4/INFO]: Completed deep scan of refinedstorageaddons-0.7.4.jar
[00:09:42] [main/INFO]: Transforming class: net.minecraft.entity.Entity
[00:09:42] [main/INFO]: Patching BlockModelShapes#getModelLocation
[00:09:42] [main/INFO]: Patching LivingEntity#attackEntityFrom
[00:09:42] [main/INFO]: Transforming method: setupTerrain net.minecraft.client.renderer.WorldRenderer
[00:09:42] [main/INFO]: Transforming method: updateCameraAndRender net.minecraft.client.renderer.WorldRenderer
[00:09:42] [main/WARN]: Static binding violation: PRIVATE @Overwrite method func_228441_a_ in rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[00:09:42] [main/WARN]: Static binding violation: PRIVATE @Overwrite method func_228437_a_ in rubidium.mixins.json:features.chunk_rendering.MixinWorldRenderer cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/532732340.call(Unknown Source)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[00:09:42] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:307)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetFancyWeather()Z in rubidium.mixins.json:features.options.MixinWorldRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap rubidium-refmap.json
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[00:09:42] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 26 more

-- Keep in mind that this isn't the exact crash log, it happened a couple of times and this is one from the time period from when I was messing around with it, so it should be the correct log, however, it could be a little different. 
I couldn't figure ANYTHING out from this log personally, but you .. maybe you can. I don't know.

**Comment by ricksouth** [comment]
Looks to be an issue with terraforged, not sure though. Unfortunately I no longer support 1.16, hope you found a solution for the issue.
