### ISSUE TITLE
Collective crashes server

### ISSUE THREAD

**Issue by catlovelia** [ricksouth/serilum-mc-mods#1973]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.22
Environment: Multiplayer

Mod name: Collective
Mod version: [Forge & Fabric] 1.19.2-6.66

## **Description**
i added collective and this happened. i removed collective and it will not go away.

## **Crash report**
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1548 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1548 failed
	at net.minecraft.class_1299.<clinit>(class_1299.java:183)
	at net.minecraft.class_3103.<clinit>(class_3103.java:28)
	at net.minecraft.class_3031.<clinit>(class_3031.java:84)
	at net.minecraft.class_6800.<clinit>(class_6800.java:20)
	at net.minecraft.class_6803.method_39702(class_6803.java:24)
	at net.minecraft.class_5458.method_44104(class_5458.java:98)
	at net.minecraft.class_5458.method_30566(class_5458.java:105)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:729)
	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)
	at net.minecraft.server.Main.main(Main.java:98)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1548 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 21 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for anticreeper.mixins.json:CreeperEntityMixin from mod anticreeper during activity: [Transform -> Method explode(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> GETSTATIC -> net/minecraft/class_1937$class_7867::field_40888:Lnet/minecraft/class_1937$class_7867;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.class_1937$class_7867
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 30 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1937$class_7867
	... 34 more

**Comment by ricksouth** [comment]
Looks like Anti Creeper causes issues

**Comment by catlovelia** [comment]
> Looks like Anti Creeper causes issues
ive never installed that. i can show u my mod list.

**Comment by ricksouth** [comment]
"Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for anticreeper.mixins.json:CreeperEntityMixin from mod anticreeper".

Maybe the mod has a different name, not sure then

**Comment by catlovelia** [comment]
> "Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for anticreeper.mixins.json:CreeperEntityMixin from mod anticreeper".
> 
> Maybe the mod has a different name, not sure then

i saw that. i only have one remotely creeper-related mod and thats creeper overhaul (makes creeper variants)

**Comment by catlovelia** [comment]
> i saw that. i only have one remotely creeper-related mod and thats creeper overhaul (makes creeper variants)

I guess it could be one other mod of mine, it splits mob greifing into 4 categories, one of which is hostile mob greifing, which is on (turns off stuff like enderman picking up blocks and creeper explosions), but those are the only mods remotely creeper or hostile mob related that I have

**Comment by catlovelia** [comment]
Found it. u were right, my apologies for wasting ur time, ill go ahead and close this, it was a mod called anticreeper I don't remember installing...

**Comment by ricksouth** [comment]
No problem, glad you figured it out!
