### ISSUE TITLE
1.19.2 collective runtime error 

### ISSUE THREAD

**Issue by LiquidMoth** [ricksouth/serilum-mc-mods#1992]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Collective 
Mod version: 1.19.2

Trying to load a fabric modpack and it wont let me due to something related to the collective mod!

Uncaught exception in thread "main"
java.lang.RuntimeException: Non-unique Mixin config name collective_fabric.mixins.json used by the mods collective and collective-fabric
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ricksouth** [comment]
Make sure to use the [Fabric & Forge] version files for all mods. And remove collective_fabric, since it's been deprecated. Thanks for the interest!
