### ISSUE TITLE
Ticking Entity crash while killing zombies.

### ISSUE THREAD

**Issue by Devestatio** [ricksouth/serilum-mc-mods#2058]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.0
Environment: Singleplayer
Mod name: Grindstone Sharper Tools
Mod version: 3.1

## **Description**
Crash to launcher, while killing Zombies with my Silent Gear Paxel, that was sharpened. Crash summary states it caused a ticking entity issue.

"Time: 2023-11-22 04:27:02
Description: Ticking entity

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?] {}
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at com.natamus.grindstonesharpertools_common_forge.util.Util.updateName(Util.java:25) ~[grindstonesharpertools-1.20.1-3.1.jar%23715!/:?] {re:classloading}
	at com.natamus.grindstonesharpertools_common_forge.events.GrindEvent.onDamage(GrindEvent.java:72) ~[grindstonesharpertools-1.20.1-3.1.jar%23715!/:?] {re:classloading}
	at com.natamus.grindstonesharpertools.forge.events.ForgeGrindEvent.onDamage(ForgeGrindEvent.java:17) ~[grindstonesharpertools-1.20.1-3.1.jar%23715!/:?] {re:classloading}
	at com.natamus.grindstonesharpertools.forge.events.__ForgeGrindEvent_onDamage_LivingHurtEvent.invoke(.dynamic) ~[grindstonesharpertools-1.20.1-3.1.jar%23715!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:292) ~[forge-1.20.1-47.2.0-universal.jar%23949!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.hammerlib.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6475_(LivingEntity.java:1617) ~[client-1.20.1-20230612.114412-srg.jar%23944!/:?]"

## **Crash report**
https://mclo.gs/WaWpXDt
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/13438795/latest.log)
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/13438784/debug.log)

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 3.3 of Grindstone Sharper Tools. Appreciate it.

https://curseforge.com/minecraft/mc-mods/grindstone-sharper-tools
