### ISSUE TITLE
Incompatibility with Valhesia Structures causing game to crash

### ISSUE THREAD

**Issue by adozenlionsroaring** [ricksouth/serilum-mc-mods#2138]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge 
Forge version: 47.2.0
Environment: Singleplayer 

First mod name: Tree Harvester
First mod version: 8.4

Second mod name: Valhesia Structures
Second mod version: 1.1.1

## **Description**

If I have both Tree Harvester and Valhesia Structures installed, the game will crash when I try to break a "Cut Oak Post" (a new type of wooden block added by Valhesia Structures). The log specifically names Tree Harvester as a conflict.

## **Crash report**

Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=axis, clazz=class net.minecraft.core.Direction$Axis, values=[x, y, z]} as it does not exist in Block{valhelsia_structures:cut_oak_post}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23904!/:?] {re:mixin,pl:connector_pre_launch:A,re:computing_frames,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin from mod ferritecore,pl:mixin:A,pl:connector_pre_launch:A}
	at com.stal111.valhelsia_structures.core.init.ModBlocks.lambda$static$22(ModBlocks.java:77) ~[valhelsia_structures-forge-1.20.1-1.1.1.jar%23876!/:1.20.1-1.1.1] {re:mixin,re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_284356_(BlockBehaviour.java:420) ~[client-1.20.1-20230612.114412-srg.jar%23904!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-object-builder-v1.mixins.json:AbstractBlockAccessor from mod fabric_object_builder_api_v1,pl:mixin:APP:forge-dramaticdoors_forge.mixins.json:BlockLootMixin from mod (unknown),pl:mixin:APP:everycomp-common.mixins.json:LootTableHackMixin from mod everycomp,pl:mixin:APP:betternether.mixins.common.json:BlockBehaviourAccessor from mod betternether,pl:mixin:APP:mixins.shetiphiancore.json:SPC_CarpetPassthrough from mod shetiphiancore,pl:mixin:APP:aether_redux.mixins.json:common.block.DoubleBlockMixin from mod aether_redux,pl:mixin:APP:betterend.mixins.common.json:BlockBehaviourMixin from mod betterend,pl:mixin:APP:beachparty-common.mixins.json:AbstractBlockMixin from mod beachparty,pl:mixin:A,pl:connector_pre_launch:A}
	at com.natamus.treeharvester_common_forge.util.Util.isGiantMushroomStemBlock(Util.java:37) ~[treeharvester-1.20.1-8.4.jar%23865!/:?] {re:classloading}
	at com.natamus.treeharvester_common_forge.util.Util.isTreeLog(Util.java:17) ~[treeharvester-1.20.1-8.4.jar%23865!/:?] {re:classloading}
	at com.natamus.treeharvester_common_forge.events.TreeCutEvents.onHarvestBreakSpeed(TreeCutEvents.java:141) ~[treeharvester-1.20.1-8.4.jar%23865!/:?] {re:classloading}
	at com.natamus.treeharvester.forge.events.ForgeTreeCutEvents.onHarvestBreakSpeed(ForgeTreeCutEvents.java:30) ~[treeharvester-1.20.1-8.4.jar%23865!/:?] {re:classloading}
	at com.natamus.treeharvester.forge.events.__ForgeTreeCutEvents_onHarvestBreakSpeed_BreakSpeed.invoke(.dynamic) ~[treeharvester-1.20.1-8.4.jar%23865!/:?] 

etc.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 8.5 of Tree Harvester.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
