### ISSUE TITLE
Valhesia Structures Cut oak post incompatibility.

### ISSUE THREAD

**Issue by 1IKing** [ricksouth/serilum-mc-mods#2174]
## **Information**
Minecraft version: 1.20.2
Modloader: Forge 
Forge version: xx.xx.xx  
Environment: Singleplayer 

First mod name: Tree Harvester
First mod version: treeharvester-1.20.1-8.6.jar

Second mod name: valhelsia_structures
Second mod version: valhelsia_structures-forge-1.20.1-1.1.1.jar

## **Description**
Modded minecraft crashed when getting to Valhesia structures. Turning off Tree Harvester fixes the crashes.

## **Crash report**
java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=axis, clazz=class net.minecraft.core.Direction$Axis, values=[x, y, z]} as it does not exist in Block{valhelsia_structures:cut_oak_post}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.stal111.valhelsia_structures.core.init.ModBlocks.lambda$static$22(ModBlocks.java:77) ~[valhelsia_structures-forge-1.20.1-1.1.1.jar%23427!/:1.20.1-1.1.1] {re:mixin,re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_284356_(BlockBehaviour.java:420) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways-common.mixins.json:MixinBlockBehaviour,pl:mixin:A}
	at com.natamus.treeharvester_common_forge.util.Util.isGiantMushroomLeafBlock(Util.java:50) ~[treeharvester-1.20.1-8.6.jar%23422!/:?] {re:classloading}
	at com.natamus.treeharvester_common_forge.events.LeafEvents.onNeighbourNotify(LeafEvents.java:84) ~[treeharvester-1.20.1-8.6.jar%23422!/:?] {re:classloading}
	at com.natamus.treeharvester.forge.events.ForgeLeafEvents.onNeighbourNotice(ForgeLeafEvents.java:31) ~[treeharvester-1.20.1-8.6.jar%23422!/:?] {re:classloading}
	at com.natamus.treeharvester.forge.events.__ForgeLeafEvents_onNeighbourNotice_NeighborNotifyEvent.invoke(.dynamic) ~[treeharvester-1.20.1-8.6.jar%23422!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onNeighborNotify(ForgeEventFactory.java:175) ~[forge-1.20.1-47.2.17-universal.jar%23449!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_46672_(ServerLevel.java:975) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_6289_(ServerLevel.java:1348) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.world.level.Level.markAndNotifyBlock(Level.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:pmmo.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6933_(Level.java:227) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:pmmo.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_7731_(Level.java:196) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:pmmo.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_7471_(Level.java:276) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:pmmo.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.block.FireBlock.tryCatchFire(FireBlock.java:228) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight.mixins.json:FireBlockMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:AccessorFireBlock,pl:mixin:APP:puzzleslib.forge.mixins.json:accessor.FireBlockForgeAccessor,pl:mixin:A}
	at net.minecraft.world.level.block.FireBlock.m_213897_(FireBlock.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight.mixins.json:FireBlockMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:AccessorFireBlock,pl:mixin:APP:puzzleslib.forge.mixins.json:accessor.FireBlockForgeAccessor,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222963_(BlockBehaviour.java:758) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:supplementaries-common.mixins.json:BlockBehaviourPlanterMixin,pl:mixin:APP:framedblocks.mixin.json:MixinBlockStateBase,pl:mixin:APP:ars_nouveau.mixins.json:redstone.RedstoneLevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:680) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:classloading}
	at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23444!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
