### ISSUE TITLE
When starting Starter-kit-6.2 Dedicated on Ubuntu with java-17sdk, errors on startup every time, clean or old world.

### ISSUE THREAD

**Issue by House-Kitty-Mew** [ricksouth/serilum-mc-mods#2244]
## **Information**
Minecraft version: 1.20.1
Modloader: Quilt
Quilt loader version: 0.23.1
Environment: Multiplayer(dedicated server)

Mod name: StarterKit
Mod version: 6.2

## **Description**
When trying to start the server on ubuntu it crashs with a null error

## **Crash report**
 Encountered an unexpected exception
java.lang.NullPointerException: Cannot read the array length because "<local5>" is null
	at com.natamus.starterkit_common_fabric.functions.StarterDataFunctions.processExistingTrackingData(StarterDataFunctions.java:91) ~[starterkit-6.2.i0:0/:?]
	at com.natamus.starterkit_common_fabric.functions.StarterDataFunctions.init(StarterDataFunctions.java:35) ~[starterkit-6.2.i0:0/:?]
	at com.natamus.starterkit_common_fabric.events.StarterServerEvents.onServerStarting(StarterServerEvents.java:18) ~[starterkit-6.2.i0:0/:?]
	at com.natamus.starterkit.ModFabric.lambda$loadEvents$0(ModFabric.java:33) ~[starterkit-6.2.i0:0/:?]
	at org.quiltmc.qsl.lifecycle.api.event.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:50) ~[quilt-lifecycle-events-6.1.21.20.1.i0:0/:?]
	at net.minecraft.server.MinecraftServer.handler$eaa000$quilt_lifecycle_events$serverStarting(MinecraftServer.java:12332) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-1.20.1.i0:0/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[15:01:34] [Server thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath: [quilt.zfs://minecraft-1.20.1.i0:0/oshi.architecture.properties, jar:file:/media/gears/1018EAF218EAD62E/servers/Minecraft/PureHorror/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.architecture.properties]
[15:01:34] [Server thread/INFO]: Mixing common.MixinServerStatus from #nochatreports:mixins/common/nochatreports.mixins.json into net.minecraft.class_2926
[15:01:34] [Server thread/ERROR]: This crash report has been saved to: /media/gears/1018EAF218EAD62E/servers/Minecraft/PureHorror/./crash-reports/crash-2024-03-04_15.01.34-server.txt
[15:01:34] [Server thread/INFO]: Stored scheduled creeper explosion event(s) to ./PureHorrorMap/./scheduled-explosions.json
[15:01:34] [Server thread/INFO]: Stopping server
[15:01:34] [Server thread/INFO]: Saving worlds
[15:01:34] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "$$5" is null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:541) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:602) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:537) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:703) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-1.20.1.i0:0/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by ricksouth** [comment]
Thank you for opening the issue! I've just uploaded version 6.3 of Starter Kit which should fix it. Could you see if it works for you?

https://curseforge.com/minecraft/mc-mods/starter-kit/files

**Comment by House-Kitty-Mew** [comment]
Issue appears to be fixed, I don't have anyone to test the co-op part yet but I don't think it will have any issues now.

**Comment by ricksouth** [comment]
Great! Thanks for confirming.
