### ISSUE TITLE
Bug with Starter Kit / Collective?

### ISSUE THREAD

**Issue by nanonestor** [ricksouth/serilum-mc-mods#2247]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.20
Environment: Multiplayer

Mod name: Starter Kit / Collective
Mod version: Starter Kit - 1.20.1-6.3 / Collective 1.20.1-7.36

## **Description**
Client crash with:
```
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "gearString" is null
	at com.natamus.collective_common_forge.functions.GearFunctions.getGearStringSplit(GearFunctions.java:413) ~[collective-1.20.1-7.36.jar%23442!/:?]
	at com.natamus.collective_common_forge.functions.GearFunctions.setInventoryFromGearString(GearFunctions.java:78) ~[collective-1.20.1-7.36.jar%23442!/:?]
	at com.natamus.starterkit_common_forge.functions.StarterClientFunctions.setCachedStarterKitInventory(StarterClientFunctions.java:85) ~[starterkit-1.20.1-6.3.jar%23610!/:?]
	at com.natamus.starterkit_common_forge.functions.StarterClientFunctions.showInitialChooseKitScreen(StarterClientFunctions.java:32) ~[starterkit-1.20.1-6.3.jar%23610!/:?]
	at com.natamus.starterkit_common_forge.functions.StarterClientFunctions.showInitialChooseKitScreen(StarterClientFunctions.java:23) ~[starterkit-1.20.1-6.3.jar%23610!/:?]
	at com.natamus.starterkit_common_forge.events.StarterClientEvents.onClientTick(StarterClientEvents.java:26) ~[starterkit-1.20.1-6.3.jar%23610!/:?]
	at com.natamus.starterkit.forge.events.ForgeStarterClientEvents.onClientTick(ForgeStarterClientEvents.java:13) ~[starterkit-1.20.1-6.3.jar%23610!/:?]
	at com.natamus.starterkit.forge.events.__ForgeStarterClientEvents_onClientTick_ClientTickEvent.invoke(.dynamic) ~[starterkit-1.20.1-6.3.jar%23610!/:?]
```
etc etc

This is the log of a user of my modpack and the client crash occurs when they try to join a dedicated multiplayer server.  I did notice they have an M1 processor, don't know if that could figure into this somehow.  Join attempts by other users work successfully.

## **Crash report**
latest.log
[latest (15).log](https://github.com/Serilum/.issue-tracker/files/14545667/latest.15.log)

List of mods
[modslist.txt](https://github.com/Serilum/.issue-tracker/files/14545669/modslist.txt)

_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 6.4 of Starter Kit.

https://curseforge.com/minecraft/mc-mods/starter-kit/files
