### ISSUE TITLE
all loot drops error

### ISSUE THREAD

**Issue by N0Tstexe** [ricksouth/serilum-mc-mods#2315]
## **Information**
Minecraft version: 1.20.4
Modloader: Forge
Forge version: 1.20.4  
Environment: Singleplayer

Mod name: all loot drops
Mod version: 3.3

## **Description**
umm so is my first time sending and error and using this but i have an issue where not all mobs would drop there loot like at all some would drop for example the spider it drops its string like 64 but the eyes like 1 or none and some other mobs wouldn't even be applied to this mod like the ghast it doesn't drop its eyes i do remember using the mod in and older version and it worked fine for all mobs but now in 1.20.4 i just dk well i hope i did this right please and thank u

**Comment by sofaemha** [comment]
## Another Error Cases

I also had problems with this mod, but different from what @N0Tstexe said

in my case, I could **NOT** create a new world when adding all-loot-drop into the mod. I'm not a java/kotlin programmer so don't know what and how the problem occurs



## Detail

here for detailed information (hopefully useful)

---

<details>
  <summary>Note</summary>

  <ol>
    <li>Collective mod WORKS FINE [ #790 ] </li>
    <li>Currently **NOT** using any of serilum mod except all-loot-drop and villager-name</li>
  </ol>
</details>

<details>
  <summary>Error: Game Crashed</summary>

<code>

The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Exception in server tick loop

Exit code: -1
</code>

---

![image](https://github.com/Serilum/.issue-tracker/assets/75196975/9a3663c3-b1e4-4945-ab2c-d333563b10fc)

</details>

<details>
  <summary>---- Minecraft Crash Report ----</summary>

<pre>
Time: 2024-04-21 11:40:47
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at net.puffish.skillsmod.SkillsMod.getPlayerServer(SkillsMod.java:642)
	at net.puffish.skillsmod.SkillsMod.getPlayerData(SkillsMod.java:638)
	at net.puffish.skillsmod.SkillsMod.refreshReward(SkillsMod.java:538)
	at net.puffish.skillsmod.api.SkillsAPI.refreshReward(SkillsAPI.java:31)
	at net.minecraft.class_3222.handler$dln000$puffish_skills$injectAtInit(class_3222.java:8468)
	at net.minecraft.class_3222.<init>(class_3222.java:285)
	at com.natamus.collective_common_fabric.fakeplayer.FakePlayer.<init>(FakePlayer.java:36)
	at com.natamus.collective_common_fabric.fakeplayer.FakePlayerFactory.lambda$get$0(FakePlayerFactory.java:29)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at com.natamus.collective_common_fabric.fakeplayer.FakePlayerFactory.get(FakePlayerFactory.java:29)
	at com.natamus.collective_common_fabric.fakeplayer.FakePlayerFactory.getMinecraft(FakePlayerFactory.java:18)
	at com.natamus.collective_common_fabric.functions.ItemFunctions.generateEntityDropsFromLootTable(ItemFunctions.java:49)
	at com.natamus.alllootdrops_common_fabric.events.EntityDroppingEvent.onWorldLoad(EntityDroppingEvent.java:34)
	at com.natamus.alllootdrops.ModFabric.lambda$loadEvents$0(ModFabric.java:30)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$0(ServerWorldEvents.java:34)
	at net.minecraft.server.MinecraftServer.redirect$bif000$fabric-lifecycle-events-v1$onLoadWorld(MinecraftServer.java:2442)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:366)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330)
	at net.minecraft.class_1132.method_3823(class_1132.java:69)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 784748688 bytes (748 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 6600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 68 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1681
	Graphics card #0 versionInfo: DriverVersion=31.0.24027.1012
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 6.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 6.40
	Memory slot #3 type: Unknown
	Virtual memory max (MB): 18034.74
	Virtual memory used (MB): 16045.71
	Swap memory total (MB): 2420.93
	Swap memory used (MB): 157.54
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 6.1.0
			libgui: LibGui 9.2.2+1.20.2
				jankson: Jankson 6.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
		additionallanterns: Additional Lanterns 1.1.1+b
		advancedcompass: Advanced Compass 1.2.16
		airhop: Air Hop 20.4.1
			cardinal-components-base: Cardinal Components API (base) 5.4.0
			cardinal-components-entity: Cardinal Components API (entities) 5.4.0
		alllootdrops: All Loot Drops 3.3
		appleskin: AppleSkin 2.5.1+mc1.20.3
		architectury: Architectury 11.1.17
		barteringstation: Bartering Station 20.4.1
		bebooks: Better Enchanted Books 1.4.5
		betteranimationscollection: Better Animations Collection 20.4.0
		bettercombat: Better Combat 1.8.6+1.20.4
		betterdeserttemples: YUNG's Better Desert Temples 1.20.4-Fabric-3.4.1
		betterdungeons: YUNG's Better Dungeons 1.20.4-Fabric-4.4.2
		betterendisland: YUNG's Better End Island 1.20.4-Fabric-2.4.1
		betterf3: BetterF3 9.0.2
		betterfortresses: YUNG's Better Nether Fortresses 1.20.4-Fabric-2.4.2
		betterjungletemples: YUNG's Better Jungle Temples 1.20.4-Fabric-2.4.1
		bettermineshafts: YUNG's Better Mineshafts 1.20.4-Fabric-4.4.1
		bettermounthud: Better Mount HUD 1.2.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20.4-Fabric-3.4.1
		betterstrongholds: YUNG's Better Strongholds 1.20.4-Fabric-4.4.1
		bettertridents: Better Tridents 20.4.0
		betterwitchhuts: YUNG's Better Witch Huts 1.20.4-Fabric-3.4.1
		bookshelf: Bookshelf 23.0.8
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 15.0.0.2
		collective: Collective 7.40
		continuity: Continuity 3.0.0-beta.4+1.20.2
		cristellib: Cristel Lib 1.2.4
			blue_endless_jankson: jankson 1.2.3
		cutthrough: Cut Through 20.4.2
		diagonalfences: Diagonal Fences 20.4.1
			diagonalblocks: Diagonal Blocks 20.4.3
		diagonalwindows: Diagonal Windows 20.4.1
		distinguishedpotions: Distinguished Potions 20.4.1
		effectdescriptions: Effect Descriptions 20.4.0
		enchdesc: EnchantmentDescriptions 20.0.3
		entity_model_features: Entity Model Features 1.3
		entity_texture_features: Entity Texture Features 5.2.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.4
		fabric-api: Fabric API 0.97.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.62+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.5+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		forgeconfigapiport: Forge Config API Port 20.4.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		glore: Glowing ores 1.2.0
		grassoverhaul: Grass Overhaul 23.10.11
		healpgood: Healing Pretty Good 1.3.2
		helditemtooltips: Held Item Tooltips 20.4.1
		hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.1.6
		horseexpert: Horse Expert 20.4.1
		iceberg: Iceberg 1.1.18
		indium: Indium 1.0.30+mc1.20.4
		infinity-cave: Infinity Cave 0.4
		inventoryprofilesnext: Inventory Profiles Next 1.10.10
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		leavemybarsalone: Leave My Bars Alone 20.4.1
		legendarytooltips: Legendary Tooltips 1.4.5
		letmedespawn: Let Me Despawn 1.2.0
		libipn: libIPN 4.0.2
		lithium: Lithium 0.12.1
		magnumtorch: Magnum Torch 20.4.0
		metalbundles: Metal Bundles 20.4.4
			iteminteractions: Item Interactions 20.4.5
		midnightlib: MidnightLib 1.5.3
		minecraft: Minecraft 1.20.4
		mobplaques: Mob Plaques 20.4.0
		modmenu: Mod Menu 9.1.0-beta.1
		moonlight: Moonlight Lib 1.20.4-2.10.3
		netherchested: Nether Chested 20.4.1
			limitlesscontainers: Limitless Containers 20.4.0
		noexperiencededuction: NoExperienceDeduction 1.0.0
		notenoughanimations: NotEnoughAnimations 1.7.1
		physicsmod: Physics Mod 3.0.13
		pickupnotifier: Pick Up Notifier 20.4.2
		playeranimator: Player Animator 1.0.2-rc1+1.20.4
		prism: Prism 1.0.6
		puffish_skills: Pufferfish's Skills 0.11.6
		puzzleslib: Puzzles Lib 20.4.42
		roughlyenoughitems: Roughly Enough Items 14.1.714
			error_notifier: Error Notifier 1.0.9
		sawmill: Universal Sawmill 1.20.4-1.3.1
		slotcycler: Slot Cycler 20.4.1
			hotbarslotcycling: Hotbar Slot Cycling 20.4.2
		sodium: Sodium 0.5.8+mc1.20.4
		sodium-extra: Sodium Extra 0.5.4+mc1.20.4-build.116
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.20.4-1.3.1
		sprintindicator: Sprint Indicator 1.3.0
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		stoneworks: Stoneworks 20.4.0
		stylisheffects: Stylish Effects 20.4.2
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		t_and_t: Towns and Towers 1.12.1
		tectonic: Tectonic 2.3.4
		terra: Terra 6.4.3-BETA+ab60f14ff
			cloud: Cloud 1.8.4
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.8.4
				cloud_commandframework_cloud-core_: cloud-core 1.8.4
				cloud_commandframework_cloud-services_: cloud-services 1.8.4
				fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
				io_leangen_geantyref_geantyref: geantyref 1.3.13
		terralith: Terralith 2.4.11
		tradingpost: Trading Post 20.4.2
		travelerstitles: Traveler's Titles 1.20.4-Fabric-4.4.0
			org_reflections_reflections: reflections 0.10.2
		trinkets: Trinkets 3.8.1
		veinmining: Vein Mining 3.1.0+1.20.4
			spectrelib: SpectreLib 0.15.2+1.20.4
		villagernames: Villager Names 7.3
		xaerominimap: Xaero's Minimap 24.1.1
		xaeroworldmap: Xaero's World Map 1.38.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20.4-Fabric-4.4.2
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20.4-Fabric-4.4.0
		yungsextras: YUNG's Extras 1.20.4-Fabric-4.4.0
		zoomify: Zoomify 2.13.2
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: MakeUp-UltraFast-8.9d.zip
		Profile: Custom (+5 options changed by user)
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, fabric, additionaladditions, additionallanterns (incompatible), barteringstation (incompatible), bettercombat, betterdeserttemples, betterdungeons, betterendisland, betterfortresses, betterjungletemples, bettermineshafts, betteroceanmonuments, betterstrongholds, bettertridents (incompatible), betterwitchhuts, bookshelf (incompatible), collective, diagonalblocks (incompatible), fabric-convention-tags-v1, grassoverhaul, healpgood, hopobetterunderwaterruins, horseexpert (incompatible), magnumtorch (incompatible), metalbundles (incompatible), moonlight, netherchested (incompatible), sawmill, stoneworks (incompatible), supermartijn642corelib (incompatible), t_and_t, terralith, tradingpost (incompatible), travelerstitles, trinkets, veinmining (incompatible), yungsbridges, yungsextras, infinity-cave:infinity-cave-terralith, tectonic/terratonic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.10-1.20.4
</pre>
</details>

[crash-2024-04-21_11.40.47-server.txt](https://github.com/Serilum/.issue-tracker/files/15050740/crash-2024-04-21_11.40.47-server.txt)

---

## Question

should I create a new issue? @ricksouth
