### ISSUE TITLE
"Fire Spread Tweaks" crashes while loading world if installed alongside "Time Shall Not Pass!"

### ISSUE THREAD

**Issue by truita** [ricksouth/serilum-mc-mods#2333]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.42 (also happens with 36.2.39, and probably any version)
Environment:  Multiplayer

First mod name: Fire Spread Tweaks
First mod version: 1.2

Second mod name: Time Shall Not Pass!
Second mod version: 1.2

## **Description**
The server will always crash before beggining world preparation.

## **Crash report**
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 4/28/24 7:06 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.Gr3atsaga.TimeShallNotPass.Config.Modules.FireTicksModule.updateDefaultGameRuleValue(FireTicksModule.java:77) ~[timeshallnotpass:1.16.5-1.2] {re:classloading}
	at com.Gr3atsaga.TimeShallNotPass.Config.Modules.FireTicksModule.onGameRuleChanged(FireTicksModule.java:64) ~[timeshallnotpass:1.16.5-1.2] {re:classloading}
	at com.Gr3atsaga.TimeShallNotPass.Config.Managers.TimeShallNotPassModuleManager$1.lambda$visit$1(TimeShallNotPassModuleManager.java:145) ~[timeshallnotpass:1.16.5-1.2] {re:classloading}
	at net.minecraft.world.GameRules$RuleValue.func_223556_a(SourceFile:272) ~[?:?] {re:classloading}
	at net.minecraft.world.GameRules$BooleanValue.func_223570_a(SourceFile:414) ~[?:?] {re:classloading}
	at com.natamus.firespreadtweaks.events.FireSpreadEvent.onWorldLoad(FireSpreadEvent.java:79) ~[firespreadtweaks:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_21_FireSpreadEvent_onWorldLoad_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:379) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:308) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:168) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 6.8.7-300.fc40.x86_64
	Java Version: 1.8.0_402, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
	Memory: 981936456 bytes (936 MB) / 1650458624 bytes (1574 MB) up to 3713531904 bytes (3541 MB)
	CPUs: 12
	JVM Flags: 0 total; 
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.42.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.42.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.42.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.42
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.42-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		firespreadtweaks_1.16.5-1.2.jar                   |Fire Spread Tweaks            |firespreadtweaks              |1.2                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.42-universal.jar                |Forge                         |forge                         |36.2.42             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		TimeShallNotPass-1.16.5-1.2.jar                   |Time Shall Not Pass           |timeshallnotpass              |1.16.5-1.2          |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-5.49.jar                        |Collective                    |collective                    |5.49                |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 0cbd5c28-0b14-4db7-9e20-c5b8ec4427e1
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:firespreadtweaks, mod:forge, mod:timeshallnotpass, mod:collective
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by ricksouth** [comment]
It looks like the nullpointer is thrown on their end. Could you open an issue on the Time Shall Not Pass github?

**Comment by truita** [comment]
Seems like the mod isn't open source so I'll try to contact him directly. Many thanks and feel free to close the issue.
