### ISSUE TITLE
Crash - Arenas 1.20.6-5.7 on Fabric calls GUI code

### ISSUE THREAD

**Issue by TigerWalts** [ricksouth/serilum-mc-mods#2350]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
Fabric loader version: 0.15.10
Environment: Multiplayer

Mod name: Areas
Mod version: 1.20.6-5.7

## **Description**
Server is crashing on start. Mod calls GUI code from Collections which tries to access a client-only class

## **Crash report**
No crash report, log file:

https://gist.github.com/TigerWalts/e07c50525882fdcd55610dbe03e161eb

```
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_332
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at com.natamus.collective_common_fabric.globalcallbacks.CollectiveGuiCallback.lambda$static$1(CollectiveGuiCallback.java:10) ~[collective-1.20.6-7.55.jar:?]
        at com.natamus.collective_common_fabric.implementations.event.ArrayBackedEvent.update(ArrayBackedEvent.java:33) ~[collective-1.20.6-7.55.jar:?]
        at com.natamus.collective_common_fabric.implementations.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:29) ~[collective-1.20.6-7.55.jar:?]
        at com.natamus.collective_common_fabric.implementations.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:32) ~[collective-1.20.6-7.55.jar:?]
        at com.natamus.collective_common_fabric.implementations.event.EventFactory.createArrayBacked(EventFactory.java:26) ~[collective-1.20.6-7.55.jar:?]
        at com.natamus.collective_common_fabric.globalcallbacks.CollectiveGuiCallback.<clinit>(CollectiveGuiCallback.java:10) ~[collective-1.20.6-7.55.jar:?]
        at com.natamus.areas_common_fabric.ModCommon.load(ModCommon.java:19) ~[areas-1.20.6-5.7.jar:?]
        at com.natamus.areas_common_fabric.ModCommon.init(ModCommon.java:13) ~[areas-1.20.6-5.7.jar:?]
        at com.natamus.areas.ModFabric.onInitialize(ModFabric.java:23) ~[areas-1.20.6-5.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
```

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 5.8 of Areas.

https://curseforge.com/minecraft/mc-mods/areas/files
