### ISSUE TITLE
Crash when collect Player Head

### ISSUE THREAD

**Issue by SgtKaneki** [ricksouth/serilum-mc-mods#2376]
## **Information**
Minecraft version:1.20.1
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer / Multiplayer (both)

Mod name: Just Mob Heads
Mod version: 7.7

## **Description**
When you break a "normal" playerhead ( /give @s minecraft:player_head ) (None specific player, just the normal Steve-Head) and want to collect it the game immediately crashes.

The Mod "Just Player Head" works fine, just "Just Mob Heads" crashes the game.

## **Crash report**
`[Server thread/WARN]: Failed to handle packet for /XYZ
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.method_10573(String, int)" because "compoundTagItemStack" is null
        at com.natamus.justmobheads_common_fabric.events.HeadDropEvent.onItemPickup(HeadDropEvent.java:145) ~[justmobheads-1.20.1-7.7.jar:?]
        at com.natamus.justmobheads.ModFabric.lambda$loadEvents$1(ModFabric.java:37) ~[justmobheads-1.20.1-7.7.jar:?]
        at com.natamus.collective.fabric.callbacks.CollectivePlayerEvents.lambda$static$8(CollectivePlayerEvents.java:48) ~[collective-1.20.1-7.57.jar:?]
        at net.minecraft.class_1542.redirect$bgi000$collective$playerTouch(class_1542.java:5564) ~[server-intermediary.jar:?]
        at net.minecraft.class_1542.method_5694(class_1542.java:360) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_7341(class_1657.java:627) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:600) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 9 more`

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 7.8 of Just Mob Heads. Appreciate it.

https://curseforge.com/minecraft/mc-mods/just-mob-heads/files
