### ISSUE TITLE
Error when loading the minecraft session with mods

### ISSUE THREAD

**Issue by jtalion41116** [ricksouth/serilum-mc-mods#2467]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: firstperson
Mod version: 2.4.3

## **Description**
When I try to enter the game then my game crashed.

## **Crash report**
[12:52:10] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.11
[12:52:10] [ForkJoinPool-1-worker-1/WARN]: Mod com_github_rtyley_animated-gif-lib-for-java uses the version animated-gif-lib-1.7 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'animated'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:52:10] [ForkJoinPool-1-worker-1/WARN]: Mod inventoryhud uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:52:11] [main/INFO]: Loading 127 mods:
	- architectury 12.1.3
	- bedrockify 1.9.5+mc1.20.6
	- betterclouds 1.6.0-beta+1.20.6.rev.28b0731
	- blur 4.0.0
	   \-- midnightlib 1.5.4
	- chunksfadein 1.0.0-1.20.3
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- crowdin-translate 1.4+1.19.3
	- cicada 0.7.2+1.20.5-and-above
	- cloth-config 14.0.126
	   \-- cloth-basic-math 0.6.1
	- connectiblechains 2.4.0+1.20.6
	- dmmttba 2.2.0
	- do_a_barrel_roll 3.6.0+1.20.6
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- mixinsquared 0.1.1
	- enchanted-vertical-slabs 1.10.4
	- entity_model_features 2.0.2
	- entity_texture_features 6.0.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- exlinefurniture 2.8.0
	- fabric-api 0.100.0+1.20.6
	   |-- fabric-api-base 0.4.40+80f8cf51b0
	   |-- fabric-api-lookup-api-v1 1.6.59+e9d2a72bb0
	   |-- fabric-biome-api-v1 13.0.25+be5d88beb0
	   |-- fabric-block-api-v1 1.0.20+6dfe4c9bb0
	   |-- fabric-block-view-api-v2 1.0.8+80f8cf51b0
	   |-- fabric-blockrenderlayer-v1 1.1.50+80f8cf51b0
	   |-- fabric-client-tags-api-v1 1.1.12+7f945d5bb0
	   |-- fabric-command-api-v1 1.2.45+f71b366fb0
	   |-- fabric-command-api-v2 2.2.24+80f8cf51b0
	   |-- fabric-commands-v0 0.2.62+df3654b3b0
	   |-- fabric-content-registries-v0 8.0.5+b82b2392b0
	   |-- fabric-convention-tags-v1 2.0.6+7f945d5bb0
	   |-- fabric-convention-tags-v2 2.1.2+bd772e83b0
	   |-- fabric-crash-report-info-v1 0.2.27+80f8cf51b0
	   |-- fabric-data-attachment-api-v1 1.1.16+2a2c66b6b0
	   |-- fabric-data-generation-api-v1 19.2.2+a5d5299db0
	   |-- fabric-dimensions-v1 2.1.68+94793913b0
	   |-- fabric-entity-events-v1 1.6.8+e9d2a72bb0
	   |-- fabric-events-interaction-v0 0.7.6+c5fc38b3b0
	   |-- fabric-game-rule-api-v1 1.0.50+80f8cf51b0
	   |-- fabric-item-api-v1 8.2.3+6e5bbc4ab0
	   |-- fabric-item-group-api-v1 4.1.0+e0fdb017b0
	   |-- fabric-key-binding-api-v1 1.0.45+80f8cf51b0
	   |-- fabric-keybindings-v0 0.2.43+df3654b3b0
	   |-- fabric-lifecycle-events-v1 2.3.4+c5fc38b3b0
	   |-- fabric-loot-api-v2 3.0.5+97f703dab0
	   |-- fabric-message-api-v1 6.0.11+a7dc0e41b0
	   |-- fabric-model-loading-api-v1 1.0.12+80f8cf51b0
	   |-- fabric-models-v0 0.4.11+9386d8a7b0
	   |-- fabric-networking-api-v1 4.1.0+3cb1a7b8b0
	   |-- fabric-object-builder-api-v1 15.1.4+c5fc38b3b0
	   |-- fabric-particles-v1 4.0.0+c5fc38b3b0
	   |-- fabric-recipe-api-v1 5.0.4+c5fc38b3b0
	   |-- fabric-registry-sync-v0 5.0.17+ad474493b0
	   |-- fabric-renderer-api-v1 3.2.12+97f703dab0
	   |-- fabric-renderer-indigo 1.5.13+8d125e3bb0
	   |-- fabric-renderer-registries-v1 3.2.61+df3654b3b0
	   |-- fabric-rendering-data-attachment-v1 0.3.46+73761d2eb0
	   |-- fabric-rendering-fluids-v1 3.1.3+2c869dedb0
	   |-- fabric-rendering-v0 1.1.64+df3654b3b0
	   |-- fabric-rendering-v1 4.2.4+b21c00cbb0
	   |-- fabric-resource-conditions-api-v1 4.2.0+a5d5299db0
	   |-- fabric-resource-loader-v0 1.1.0+c0e5481fb0
	   |-- fabric-screen-api-v1 2.0.21+7b70ea8ab0
	   |-- fabric-screen-handler-api-v1 1.3.74+8c7b71c2b0
	   |-- fabric-sound-api-v1 1.0.21+c5fc38b3b0
	   |-- fabric-transfer-api-v1 5.1.6+c5fc38b3b0
	   \-- fabric-transitive-access-wideners-v1 6.0.10+74e2f560b0
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- fallingtree 1.20.6.3
	- fancymenu 3.2.3
	   |-- com_github_keksuccino_japng 0.5.3
	   \-- com_github_rtyley_animated-gif-lib-for-java animated-gif-lib-1.7
	- farlandsreborn 1.0.0
	- firstperson 2.4.3
	- fpsdisplay 4.1.0+1.20.5
	- frozenlib 1.7.2-Fabric+1.20.6
	- ftblibrary 2006.1.2
	- ftbultimine 2006.1.0
	- inventoryhud ${version}
	- java 21
	- konkrete 1.9.4
	- melody 1.0.6
	- minecraft 1.20.6
	- modmenu 10.0.0-beta.1
	- mr_ketkets_furnicraft 2.5
	- nodurability 1.7.0
	- pehkui 3.8.3+1.14.4-1.21
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- reeses-sodium-options 1.7.2+mc1.20.5-build.103
	- simple_copper_pipes 2.0
	- sit 1.20.6-27
	- sodium 0.5.8+mc1.20.4
	- sodium-extra 0.5.5+mc1.20.6-build.118
	   \-- caffeineconfig 1.3.0+1.17
	- stackable 1.2.0
	- vmtranslationupdate 2.4.0+mc1.20.6
	- voicechat 1.20.6-2.5.15
	- worldedit 7.3.3+6788-6359df8
	- yet_another_config_lib_v3 3.4.4+1.20.6-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zoomify 2.13.5+1.20.6
	   |-- com_akuleshov7_ktoml-core-jvm 0.5.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
[12:52:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/jtali/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:52:13] [main/INFO]: Compatibility level set to JAVA_16
[12:52:13] [main/INFO]: Compatibility level set to JAVA_17
[12:52:13] [main/INFO]: Compatibility level set to JAVA_21
[12:52:17] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[12:52:17] [main/INFO]: Loaded configuration file for Sodium Extra: 35 options available, 0 override(s) found
[12:52:19] [main/WARN]: Error loading class: net/irisshaders/iris/pipeline/programs/ExtendedShader (java.lang.ClassNotFoundException: net/irisshaders/iris/pipeline/programs/ExtendedShader)
[12:52:19] [main/WARN]: @Mixin target net.irisshaders.iris.pipeline.programs.ExtendedShader was not found betterclouds.optional.mixins.json:ExtendedShaderAccessor from mod betterclouds
[12:52:19] [main/WARN]: Error loading class: net/irisshaders/iris/pipeline/programs/FallbackShader (java.lang.ClassNotFoundException: net/irisshaders/iris/pipeline/programs/FallbackShader)
[12:52:19] [main/WARN]: @Mixin target net.irisshaders.iris.pipeline.programs.FallbackShader was not found betterclouds.optional.mixins.json:FallbackShaderAccessor from mod betterclouds
[12:52:20] [main/WARN]: Error loading class: net/raphimc/immediatelyfast/feature/core/ImmediateAdapter (java.lang.ClassNotFoundException: net/raphimc/immediatelyfast/feature/core/ImmediateAdapter)
[12:52:20] [main/WARN]: Error loading class: net/coderbot/batchedentityrendering/impl/FullyBufferedMultiBufferSource (java.lang.ClassNotFoundException: net/coderbot/batchedentityrendering/impl/FullyBufferedMultiBufferSource)
[12:52:20] [main/WARN]: Error loading class: net/coderbot/iris/layer/InnerWrappedRenderType (java.lang.ClassNotFoundException: net/coderbot/iris/layer/InnerWrappedRenderType)
[12:52:20] [main/WARN]: Error loading class: net/coderbot/iris/layer/OuterWrappedRenderType (java.lang.ClassNotFoundException: net/coderbot/iris/layer/OuterWrappedRenderType)
[12:52:20] [main/WARN]: Error loading class: net/irisshaders/batchedentityrendering/impl/FullyBufferedMultiBufferSource (java.lang.ClassNotFoundException: net/irisshaders/batchedentityrendering/impl/FullyBufferedMultiBufferSource)
[12:52:20] [main/WARN]: Error loading class: net/irisshaders/iris/layer/InnerWrappedRenderType (java.lang.ClassNotFoundException: net/irisshaders/iris/layer/InnerWrappedRenderType)
[12:52:20] [main/WARN]: Error loading class: net/irisshaders/iris/layer/OuterWrappedRenderType (java.lang.ClassNotFoundException: net/irisshaders/iris/layer/OuterWrappedRenderType)
[12:52:20] [main/WARN]: Error loading class: dev/tr7zw/skinlayers/render/CustomizableModelPart (java.lang.ClassNotFoundException: dev/tr7zw/skinlayers/render/CustomizableModelPart)
[12:52:27] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[12:52:27] [main/INFO]: Searching for graphics cards...
[12:52:30] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Intel(R) HD Graphics 630, version=27.20.100.8280]
[12:52:32] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[12:53:20] [Render thread/ERROR]: Mixin apply for mod sodium failed sodium.mixins.json:features.render.immediate.matrix_stack.VertexConsumerMixin from mod sodium -> net.minecraft.class_4588: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Overwrite method method_23763 in sodium.mixins.json:features.render.immediate.matrix_stack.VertexConsumerMixin from mod sodium was not located in the target class net.minecraft.class_4588. Using refmap sodium.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Overwrite method method_23763 in sodium.mixins.json:features.render.immediate.matrix_stack.VertexConsumerMixin from mod sodium was not located in the target class net.minecraft.class_4588. Using refmap sodium.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) [?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) [?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) [?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) [?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	at net.minecraft.class_289.<init>(class_289.java:33) [client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(RenderSystem.java:50) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:220) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
[12:53:21] [Render thread/INFO]: fpsdisplay.mixins.json:MinecraftClientAccessor from mod fpsdisplay->@Accessor[FIELD_GETTER]::getCurrentFps()I should be static as its target is
[12:53:21] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2589) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2564) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:233) ~[fabric-loader-0.15.11-1.20.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 2 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4588 failed [in thread "Render thread"]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_289.<init>(class_289.java:33) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(RenderSystem.java:50) ~[fabric-loader-0.15.11-1.20.6.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:220) ~[fabric-loader-0.15.11-1.20.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 2 more

If available.

**Comment by ricksouth** [comment]
You don't have any of my mods installed, why are you opening an issue here?
