### ISSUE TITLE
YIAS not generates chest if there's no space

### ISSUE THREAD

**Issue by bangetto** [ricksouth/serilum-mc-mods#2584]
## **Information**
Minecraft version: 1.20.1
Modloader:vFabric
Forge version: xx.xx.xx  OR  Fabric loader version: 0.15.11
Environment: Multiplayer

Mod name: Your Items Are Safe
Mod version: 4.5

## **Description**
I managed to die in a 1x1x2 space and the chest with my inventory haven't generated for some reason, even though the chat said it did.
Tomorrow I will try to recreate the scenario to get more information

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by James103** [comment]
Did this result in the immediate voiding of your entire inventory, with no way to recover it unless you had a death backup mod installed?

**Comment by bangetto** [comment]
only the armor stand generated, the other items were destroyed

**Comment by bangetto** [comment]
Here is some of the log from that time idk if it's helps
<details><summary>Details</summary>
<p>

```
[17:12:53] [Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.ClassCastException: class net.minecraft.class_5837 cannot be cast to class net.minecraft.class_2561 (net.minecraft.class_5837 and net.minecraft.class_2561 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @97e1986)
	at net.minecraft.class_3244.handler$bgl000$craterlib$injectChatEvent(class_3244.java:1971) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_45064(class_3244.java) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:13318) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[17:21:53] [Server thread/INFO]: bangetto was run over by Iron Train
[17:21:54] [Server thread/WARN]: Unable to resolve BlockEntity for ItemStack: fxntstorage:copper_back_pack
``` 

</p>
</details>
