### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by DJDEADWOLF** [ricksouth/serilum-mc-mods#2591]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Multiplayer

Mod name: Collective
Mod version: 7.64

## **Description**
Hey! This happened,

## **Crash report**
[1;31m[05:34:59 ERROR] [FabricLoader/Mixin]: Mixin apply for mod collective failed collective_fabric.mixins.json:PlayerMixin from mod collective -> net.minecraft.class_1657: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Implicit variable modifier injection failed in net/minecraft/class_1657::Player_attack [INJECT Applicator Phase -> collective_fabric.mixins.json:PlayerMixin from mod collective -> Apply Injections ->  -> Inject -> collective_fabric.mixins.json:PlayerMixin from mod collective->@ModifyVariable::Player_attack(Lnet/minecraft/class_1799;Lnet/minecraft/class_1297;)Lnet/minecraft/class_1799;]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Implicit variable modifier injection failed in net/minecraft/class_1657::Player_attack [INJECT Applicator Phase -> collective_fabric.mixins.json:PlayerMixin from mod collective -> Apply Injections ->  -> Inject -> collective_fabric.mixins.json:PlayerMixin from mod collective->@ModifyVariable::Player_attack(Lnet/minecraft/class_1799;Lnet/minecraft/class_1297;)Lnet/minecraft/class_1799;]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:216) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]

If available.

**Comment by UplandJacob** [comment]
Seems to be the same as #2308
