### ISSUE TITLE
Possible incompatibility between Areas and Supplementaries

### ISSUE THREAD

**Issue by Lucky44x** [ricksouth/serilum-mc-mods#2596]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.3.0
Environment: Singleplayer

First mod name: Supplementaries / Amendments
First mod version: 1.20-2.8.17 / 1.20-1.2.8

Second mod name: Random Village Names / Areas
Second mod version: 1.20.1-3.7 / 1.20.1-6.0

NOTE: I think this concerns mainly Areas

## **Description**
I was building myself a modpack and areas with random village names worked fine, until I added Supplementaries + Amendments (although Amendments doesn't include signposts...)
After adding the mods, the areas command no longer functioned and instead threw an error

I took a look in the logs and it seems like it's a cast exception:
```
Error executing client command "areas"
java.lang.ClassCastException: class net.mehvahdjukaar.supplementaries.common.block.tiles.SignPostBlockTile cannot be cast to class net.minecraft.world.level.block.entity.SignBlockEntity (net.mehvahdjukaar.supplementaries.common.block.tiles.SignPostBlockTile is in module supplementaries@1.20-2.8.17 of loader 'TRANSFORMER' @750c23a3; net.minecraft.world.level.block.entity.SignBlockEntity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @750c23a3)
	at com.natamus.areas_common_forge.cmds.ClientCommandAreas.areas(ClientCommandAreas.java:56) ~[areas-1.20.1-6.0.jar%23374!/:?]
	at com.natamus.areas_common_forge.cmds.ClientCommandAreas.lambda$register$1(ClientCommandAreas.java:36) ~[areas-1.20.1-6.0.jar%23374!/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%23113!/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.1.8.jar%23113!/:?]
	at net.minecraftforge.client.ClientCommandHandler.runCommand(ClientCommandHandler.java:161) ~[forge-1.20.1-47.3.0-universal.jar%23565!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_246623_(ClientPacketListener.java:2418) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.gui.screens.ChatScreen.m_241797_(ChatScreen.java:223) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.gui.screens.ChatScreen.m_7933_(ChatScreen.java:101) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$5(KeyboardHandler.java:379) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:369) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:462) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:461) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23153!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

I've also run the mod in an isolated instance with just random village names, areas and village spawn point, and it ran fine....
after adding in Supplementaries however the predictable happened and it started throwing errors again

So: Suppl. Sign Post tiles do not (or no longer... idk) inherit from sign-entities

Quick temporary fix (I know I should be ashamed of myself for this): Stick whatever function is throwing the error in a try-catch block and abort / skip the iteration step when it catches an exception

For completeness sake, here's the whole log:
[latest.log](https://github.com/user-attachments/files/16663548/latest.log)

And the less cluttered Isolated instance log:
[latest.log](https://github.com/user-attachments/files/16663594/latest.log)

**Comment by Abrinsky** [comment]
Can confirm this is still an issue, making areas and random village names unusable with my own pack that I am making with Supplementaries / Amendments as well
