### ISSUE TITLE
Compat issue and Client Crash with ETF and Collective Lib

### ISSUE THREAD

**Issue by suerion** [ricksouth/serilum-mc-mods#2756]
## **Information**
Minecraft version: 1.21.1
 Fabric loader version: 0.16.9
Client Crash

First mod name: Mod entity_texture_features_fabric_1.21.1-6.2.7.jar

Second mod name: Mod collective-1.21.1-7.87.jar

## **Description**
Hey, had disabled all Mods and tried to found the issue and culprit from my huge modpack. https://github.com/Traben-0/Entity_Texture_Features/issues/320

it is a compatibilty issue with ETF and Collective, with ETF alone it does work, with Collective also alone, but together it crash allways my client

## **Crash report**
https://mclo.gs/pGvQmua

**Comment by suerion** [comment]
Hey, had this issue again with useless reptiles

https://mclo.gs/znEYYb4


-> The issue is given like the issue above 


```
[14:51:24] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'uselessreptile' at 'nordmods.uselessreptile.UselessReptile'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.13.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'uselessreptile' at 'nordmods.uselessreptile.UselessReptile'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.13.jar:?]
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at knot/net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.42+6573ed8c19-790e1f946d4fbbbd.jar:?]
	at knot/net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.42+6573ed8c19-790e1f946d4fbbbd.jar:?]
	at knot/com.natamus.collective.fabric.callbacks.CollectiveLifecycleEvents.<clinit>(CollectiveLifecycleEvents.java:9) ~[collective-1.21.1-8.1.jar:?]
	at knot/net.minecraft.class_2477.handler$dhb000$collective$loadDefault(class_2477.java:3514) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2477.method_29429(class_2477.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2477.<clinit>(class_2477.java:36) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2588.method_11025(class_2588.java:101) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2588.method_27659(class_2588.java:196) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.method_27657(class_2561.java:114) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5348.getString(class_5348.java:91) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.getString(class_2561.java:45) ~[client-intermediary.jar:?]
	at knot/traben.entity_texture_features.config.ETFConfig$IllegalPathMode.toString(ETFConfig.java:459) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:888) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.TypeAdapters$29.create(TypeAdapters.java:930) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1226) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1075) ~[gson-2.10.1.jar:?]
	at knot/traben.tconfig.TConfigHandler.fromJson(TConfigHandler.java:127) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.tconfig.TConfigHandler.loadFromFile(TConfigHandler.java:103) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.tconfig.TConfigHandler.<init>(TConfigHandler.java:35) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.entity_texture_features.ETF.config(ETF.java:44) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/net.minecraft.class_2960.handler$eod000$entity_texture_features$etf$illegalPathOverride(class_2960.java:1019) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_20208(class_2960.java:256) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_45137(class_2960.java:284) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_60656(class_2960.java:60) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2583.<clinit>(class_2583.java:39) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5250.method_43477(class_5250.java:29) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.method_43471(class_2561.java:229) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.<clinit>(class_2960.java:30) ~[client-intermediary.jar:?]
	at knot/nordmods.uselessreptile.UselessReptile.id(UselessReptile.java:43) ~[useless-reptile-0.9.8-1.21.1.jar:?]
	at knot/nordmods.uselessreptile.common.config.URConfig.<clinit>(URConfig.java:11) ~[useless-reptile-0.9.8-1.21.1.jar:?]
	at knot/nordmods.uselessreptile.UselessReptile.onPreLaunch(UselessReptile.java:39) ~[useless-reptile-0.9.8-1.21.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.13.jar:?]
	... 2 more
Caused by: java.lang.IllegalStateException: Detected recursive translation: options.off
	at knot/net.minecraft.class_2588.handler$mio000$specter-serialization$push(class_2588.java:2040) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2588.method_27659(class_2588.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.method_27657(class_2561.java:114) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5348.getString(class_5348.java:91) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.getString(class_2561.java:45) ~[client-intermediary.jar:?]
	at knot/traben.entity_texture_features.config.ETFConfig$IllegalPathMode.toString(ETFConfig.java:459) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:888) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.TypeAdapters$29.create(TypeAdapters.java:930) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.toJson(Gson.java:834) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.toJson(Gson.java:812) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.toJson(Gson.java:759) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.toJson(Gson.java:736) ~[gson-2.10.1.jar:?]
	at knot/traben.tconfig.TConfigHandler.toJson(TConfigHandler.java:90) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.tconfig.TConfigHandler.toJson(TConfigHandler.java:86) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.tconfig.TConfigHandler.saveToFile(TConfigHandler.java:79) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.tconfig.TConfigHandler.loadFromFile(TConfigHandler.java:117) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.tconfig.TConfigHandler.<init>(TConfigHandler.java:35) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.entity_texture_features.ETF.config(ETF.java:44) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/net.minecraft.class_2960.handler$eod000$entity_texture_features$etf$illegalPathOverride(class_2960.java:1019) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_20208(class_2960.java:256) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_45137(class_2960.java:284) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_60936(class_2960.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_60655(class_2960.java:52) ~[client-intermediary.jar:?]
	at knot/net.fabricmc.fabric.api.event.Event.<clinit>(Event.java:63) ~[fabric-api-base-0.4.42+6573ed8c19-790e1f946d4fbbbd.jar:?]
	at knot/net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.42+6573ed8c19-790e1f946d4fbbbd.jar:?]
	at knot/net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.42+6573ed8c19-790e1f946d4fbbbd.jar:?]
	at knot/com.natamus.collective.fabric.callbacks.CollectiveLifecycleEvents.<clinit>(CollectiveLifecycleEvents.java:9) ~[collective-1.21.1-8.1.jar:?]
	at knot/net.minecraft.class_2477.handler$dhb000$collective$loadDefault(class_2477.java:3514) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2477.method_29429(class_2477.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2477.<clinit>(class_2477.java:36) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2588.method_11025(class_2588.java:101) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2588.method_27659(class_2588.java:196) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.method_27657(class_2561.java:114) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5348.getString(class_5348.java:91) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.getString(class_2561.java:45) ~[client-intermediary.jar:?]
	at knot/traben.entity_texture_features.config.ETFConfig$IllegalPathMode.toString(ETFConfig.java:459) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:888) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.TypeAdapters$29.create(TypeAdapters.java:930) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1226) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1075) ~[gson-2.10.1.jar:?]
	at knot/traben.tconfig.TConfigHandler.fromJson(TConfigHandler.java:127) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.tconfig.TConfigHandler.loadFromFile(TConfigHandler.java:103) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.tconfig.TConfigHandler.<init>(TConfigHandler.java:35) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/traben.entity_texture_features.ETF.config(ETF.java:44) ~[entity_texture_features_fabric_1.21.1-6.2.9.jar:?]
	at knot/net.minecraft.class_2960.handler$eod000$entity_texture_features$etf$illegalPathOverride(class_2960.java:1019) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_20208(class_2960.java:256) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_45137(class_2960.java:284) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_60656(class_2960.java:60) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2583.<clinit>(class_2583.java:39) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5250.method_43477(class_5250.java:29) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.method_43471(class_2561.java:229) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.<clinit>(class_2960.java:30) ~[client-intermediary.jar:?]
	at knot/nordmods.uselessreptile.UselessReptile.id(UselessReptile.java:43) ~[useless-reptile-0.9.8-1.21.1.jar:?]
	at knot/nordmods.uselessreptile.common.config.URConfig.<clinit>(URConfig.java:11) ~[useless-reptile-0.9.8-1.21.1.jar:?]
	at knot/nordmods.uselessreptile.UselessReptile.onPreLaunch(UselessReptile.java:39) ~[useless-reptile-0.9.8-1.21.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.13.jar:?]
	... 2 more

```

**Comment by harrrobe** [comment]
same issue pls help
