### ISSUE TITLE
Causes "RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by" error with all installed mods

### ISSUE THREAD

**Issue by x4740N** [ricksouth/serilum-mc-mods#2826]
## **Information**
Minecraft version: 1.21.4
Modloader: Fabric
Fabric loader version: 0.16.9
Environment: Singleplayer

Mod name: Collective
Mod version: 7.89

## **Description**
As the title says this mod causes "RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by" error with all mods installed

I've tried disabling mods but every one i have disabled keeps popping up with the same error, the issue goes away if i disabled collective by renaming it's file extension

I dont see the point to wasting time by testing every mod because ive tested multiple already and they've all had the issue so the issue is likely with the collective mod

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

Here is a crashlog with one of the mods but it happens with all installed mods

```
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'ok_zoomer' at 'io.github.ennuil.ok_zoomer.OkZoomerPreLaunchMod'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'ok_zoomer' at 'io.github.ennuil.ok_zoomer.OkZoomerPreLaunchMod'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'ok_zoomer'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of io.github.ennuil.ok_zoomer.OkZoomerPreLaunchMod failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [profundis.mixins.json:VanillaBiomeParametersMixin from mod profundis] from phase [DEFAULT] in config [profundis.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'firenh.profundis.mixin.VanillaBiomeParametersMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:864)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:933)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:858)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 20 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'firenh.profundis.mixin.VanillaBiomeParametersMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1318)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857)
	... 23 more

```

**Comment by ricksouth** [comment]
I believe this has been fixed in the latest version due to another related problem. Please let me know if the issue persists, thanks for giving some of the mods a try!
