### ISSUE TITLE
Just Mob Heads (Fabric) Compat issue with "More Axolotl Variants" ??

### ISSUE THREAD

**Issue by TheLegitStick** [ricksouth/serilum-mc-mods#722]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: 0.11.6
Environment: Multiplayer

Mod name: Just Mob Heads (Fabric)
Mod version: 4.2

## **Description**
Hey! There seems to be a compat issue with, im assuming, More Axolotl Variants. It's a classic ticking entity error

## **Crash report**
---- Minecraft Crash Report ----
// Sorry :(

Time: 9/29/21, 1:46 AM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 5
	at java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at com.natamus.justmobheads.util.MobHeads.getName(MobHeads.java:157)
	at com.natamus.justmobheads.events.HeadDropEvent.mobItemDrop(HeadDropEvent.java:33)
	at com.natamus.justmobheads.Main.lambda$registerEvents$0(Main.java:28)
	at com.natamus.collective_fabric.fabric.callbacks.CollectiveEntityEvents.lambda$static$12(CollectiveEntityEvents.java:65)
	at net.minecraft.entity.LivingEntity.handler$baa000$dropAllDeathLoot(LivingEntity:8615)
	at net.minecraft.entity.LivingEntity.drop(LivingEntity:1374)
	at net.minecraft.entity.LivingEntity.onDeath(LivingEntity:1324)
	at net.minecraft.entity.LivingEntity.damage(LivingEntity:1177)
	at net.minecraft.entity.passive.AnimalEntity.damage(AnimalEntity:78)
	at net.minecraft.entity.passive.AxolotlEntity.damage(AxolotlEntity:403)
	at net.minecraft.entity.LivingEntity.handleFallDamage(LivingEntity:1519)
	at net.minecraft.block.Block.onLandedUpon(Block:464)
	at net.minecraft.entity.Entity.fall(Entity:1153)
	at net.minecraft.entity.LivingEntity.fall(LivingEntity:318)
	at net.minecraft.entity.Entity.move(Entity:640)
	at net.minecraft.entity.LivingEntity.method_26318(LivingEntity:2244)
	at net.minecraft.entity.LivingEntity.travel(LivingEntity:2189)
	at net.minecraft.entity.passive.AxolotlEntity.travel(AxolotlEntity:570)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2640)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:539)
	at net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity:127)
	at net.minecraft.entity.passive.AnimalEntity.tickMovement(AnimalEntity:55)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2346)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:339)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:655)
	at net.minecraft.world.World.tickEntity(World:483)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:417)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:392)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:891)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:335)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:831)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:831)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at com.natamus.justmobheads.util.MobHeads.getName(MobHeads.java:157)
	at com.natamus.justmobheads.events.HeadDropEvent.mobItemDrop(HeadDropEvent.java:33)
	at com.natamus.justmobheads.Main.lambda$registerEvents$0(Main.java:28)
	at com.natamus.collective_fabric.fabric.callbacks.CollectiveEntityEvents.lambda$static$12(CollectiveEntityEvents.java:65)
	at net.minecraft.class_1309.handler$baa000$dropAllDeathLoot(class_1309.java:8615)
	at net.minecraft.class_1309.method_16080(class_1309.java:1374)
	at net.minecraft.class_1309.method_6078(class_1309.java:1324)
	at net.minecraft.class_1309.method_5643(class_1309.java:1177)
	at net.minecraft.class_1429.method_5643(class_1429.java:78)
	at net.minecraft.class_5762.method_5643(class_5762.java:403)
	at net.minecraft.class_1309.method_5747(class_1309.java:1519)
	at net.minecraft.class_2248.method_9554(class_2248.java:464)
	at net.minecraft.class_1297.method_5623(class_1297.java:1153)
	at net.minecraft.class_1309.method_5623(class_1309.java:318)
	at net.minecraft.class_1297.method_5784(class_1297.java:640)
	at net.minecraft.class_1309.method_26318(class_1309.java:2244)
	at net.minecraft.class_1309.method_6091(class_1309.java:2189)
	at net.minecraft.class_5762.method_6091(class_5762.java:570)
	at net.minecraft.class_1309.method_6007(class_1309.java:2640)
	at net.minecraft.class_1308.method_6007(class_1308.java:539)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:55)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1308.method_5773(class_1308.java:339)
	at net.minecraft.class_3218.method_18762(class_3218.java:655)

-- Entity being ticked --
Details:
	Entity Type: minecraft:axolotl (net.minecraft.class_5762)
	Entity ID: 6151
	Entity Name: Axolotl
	Entity's Exact location: -267.22, 25.00, -79.38
	Entity's Block location: World: (-268,25,-80), Section: (at 4,9,0 in -17,1,-5; chunk contains blocks -272,0,-80 to -257,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: -0.00, -0.93, -0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Age:0,Air:5986s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:1.0d,Name:"minecraft:generic.movement_speed"},{Base:16.0d,Modifiers:[{Amount:-0.016150392286344625d,Name:"Random spawn bonus",Operation:1,UUID:[I;1070780266,-830454244,-1564625482,745350023]}],Name:"minecraft:generic.follow_range"}],Brain:{memories:{}},CanPickUpLoot:0b,DeathTime:0s,FallDistance:6.0256834f,FallFlying:0b,Fire:-1s,ForcedAge:0,FromBucket:0b,HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:0.0f,HurtByTimestamp:0,HurtTime:10s,InLove:0,Invulnerable:0b,LeftHanded:0b,Motion:[-0.003772420337878262d,-0.9322026084022045d,-0.0018755827879364275d],OnGround:1b,PersistenceRequired:0b,PortalCooldown:0,Pos:[-267.21910811335226d,25.0d,-79.37687558278793d],Rotation:[247.49512f,5.0f],UUID:[I;570649725,-1061990650,-1663389366,-206775660],Variant:8}
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:523)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.world.World.addDetailsToCrashReport(World:845)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:894)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:335)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:831)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:831)

-- Affected level --
Details:
	All players: 1 total; [class_3222['TheLegitStick'/561, l='ServerLevel[blockbound]', x=-358.71, y=26.00, z=-71.49]]
	Chunk stats: 3958
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,81,-256), Section: (at 0,1,0 in 11,5,-16; chunk contains blocks 176,0,-256 to 191,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 5586882 game time, 7109461 day time
	Level name: blockbound
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 29786 (now: false), thunder time: 48393 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 4.19.0-14-amd64
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 7095231864 bytes (6766 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3950X 16-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 129856.83
	Virtual memory used (MB): 75920.80
	Swap memory total (MB): 65392.99
	Swap memory used (MB): 7559.23
	JVM Flags: 20 total; -Xms8192M -Xmx8192M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.5.28
		attributefix: Attribute Fix {FABRIC} 1.0.3
		audiooutput: AudioOutput 0.0.4
		beaconoverhaul: Beacon Overhaul 1.4.1+1.17
		bedspreads: Bedspreads 1.4.0-1.17
		betterbeds: Better Beds 1.2.0
		blast: BLAST 1.7
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		charm: Charm 3.3.2
		chat_plus: Chat+ 2.1.5
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		collective-fabric: Collective (Fabric) 1.41
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_meteordevelopment_starscript: starscript 0.1.5
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		companion_bats: Companion Bats 1.17.8
		dawn: Dawn API 2.0.6
		deathlog: DeathLog 0.2.1
		doublejump: Double Jump Mod 1.0.1+mc1.17
		draggable-resource-packs: Draggable Resource Packs 1.0.1
		dual_riders: DualRiders 1.0.5
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabrication: Fabrication 2.0.0-pre4
		fabricloader: Fabric Loader 0.11.6
		farmersdelight: Farmer's Delight 1.17.1-0.1.2
		fastfurnace: FastFurnace 1.17-3.0
		fiber: fiber 0.23.0-2
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		goosiklib: Goosik Lib 0.1.0
		inventorio: Inventorio 1.6.2
		java: OpenJDK 64-Bit Server VM 16
		justmobheads-fabric: Just Mob Heads (Fabric) 4.2
		justplayerheads-fabric: Just Player Heads (Fabric) 1.8
		krypton: Krypton 0.1.4
		ksrch: Keybind Search 1.0.0
		lakeside: Lakeside 1.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libjf: LibJF 1.2.3
		light-fix: light-fix 1.0.0
		lithium: Lithium 0.7.4
		lovely_snails: Lovely Snails 1.0.3+1.17
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		me_hypherionmc_simple-rpc-lib: simple-rpc-lib 2.1.10
		midnightlib: MidnightLib 0.2.5
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.1
		morebannerfeatures: More Banner Features 1.0.7
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		notenoughcrashes: Not Enough Crashes 3.6.4+1.17.1
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		placeholder-api: Fabric Placeholder API 1.0.0-rc2-1.17
		polymorph: Polymorph 0.0.14-1.17.1
		pride: Pride Lib 1.0.0+21w03a
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.3.4+1.17.1
		riverredux: River Redux 0.2.0
		rocks: This Rocks! 1.5.0
		simple-rpc: Simple Rpc 1.17-2.4-fabric
		spark: spark 1.6.1
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		styledplayerlist: Styled Player List 2.1.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		universal_ores: Universal Ores 1.0
		vanilla_degus: Vanilla Degus 1.2.0
		voicechat: Simple Voice Chat 1.17.1-1.2.0
		wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
	Player Count: 1 / 69; [class_3222['TheLegitStick'/561, l='ServerLevel[blockbound]', x=-358.71, y=26.00, z=-71.49]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: Collective (Fabric) (collective-fabric), Just Mob Heads (Fabric) (justmobheads-fabric)

**Comment by ricksouth** [comment]
Apologies for the late response. I've fixed the problem in version 5.0 of Just Mob Heads. Thanks for giving the mod a try and opening the bug report!

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads-fabric/files/all
