### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#753]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge / Fabric
Fabric loader version: 0.11.6
Environment: Multiplayer

Mod name: nether portal spread
Mod version: 5.4

## **Description**
Mod crashes on startup

## **Crash report**
[21:45:44] [main/INFO]: Loading for game Minecraft 1.16.5
[21:45:45] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "/home/minecraft/multicraft/servers/server1042233/mods/SimpleJail-1.16--1.1.3.jar", ignoring
[21:45:45] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "/home/minecraft/multicraft/servers/server1042233/mods/DarkPaintings-1.16.5-6.0.3.jar", ignoring
[21:45:45] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "/home/minecraft/multicraft/servers/server1042233/mods/Patchouli-1.16.4-53.2.jar", ignoring
[21:45:45] [main/INFO]: [FabricLoader] Loading 153 mods:
	- angerable-patch@1.1.0-1.16.4
	- architectury@1.23.33
	- autoconfig1u@3.3.1
	- betterf3@1.1.3
	- campanion@1.3.5
	- cardinal-components@2.8.3
	- cardinal-components-base@2.8.3
	- cardinal-components-block@2.8.3
	- cardinal-components-chunk@2.8.3
	- cardinal-components-entity@2.8.3
	- cardinal-components-item@2.8.3
	- cardinal-components-level@2.8.3
	- cardinal-components-scoreboard@2.8.3
	- cardinal-components-util@2.8.3
	- cardinal-components-world@2.8.3
	- charm@2.3.2
	- chat_heads@0.2.2+1.16.2
	- cinderscapes@1.4.0
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@1.5.47
	- cloth-config2@4.11.24
	- club_minnced_discord-webhooks@0.5.7
	- collective-fabric@1.48
	- com_electronwill_night-config_core@3.6.3
	- com_electronwill_night-config_toml@3.6.3
	- com_fasterxml_jackson_core_jackson-annotations@2.10.1
	- com_fasterxml_jackson_core_jackson-core@2.10.1
	- com_fasterxml_jackson_core_jackson-databind@2.10.1
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_neovisionaries_nv-websocket-client@2.14
	- com_squareup_okhttp3_okhttp@3.14.9
	- com_squareup_okio_okio@1.17.2
	- com_vdurmont_emoji-java@5.1.1
	- couplings@1.5.0+1.16
	- croptopia@1.4.0
	- curios@0.0.13-1.16.5
	- customportals@1.4.2
	- darkness@1.6.58
	- dynmap@3.2.1
	- elementalcreepers@1.3.0
	- enderitemod@1.2.4
	- fabric@0.32.5+1.16
	- fabric-api-base@0.3.0+c88702897d
	- fabric-api-lookup-api-v1@1.0.0+dc716ea17d
	- fabric-biome-api-v1@3.1.1+ca58154a7d
	- fabric-blockrenderlayer-v1@1.1.5+ca58154a7d
	- fabric-command-api-v1@1.1.1+351679a77d
	- fabric-commands-v0@0.2.2+ca58154a7d
	- fabric-containers-v0@0.1.11+9354966b7d
	- fabric-content-registries-v0@0.2.1+ca58154a7d
	- fabric-crash-report-info-v1@0.1.3+ca58154a7d
	- fabric-dimensions-v1@2.0.6+9354966b7d
	- fabric-entity-events-v1@1.0.3+ca58154a7d
	- fabric-events-interaction-v0@0.4.2+ca58154a7d
	- fabric-events-lifecycle-v0@0.2.1+ca58154a7d
	- fabric-game-rule-api-v1@1.0.6+ca58154a7d
	- fabric-item-api-v1@1.2.1+ca58154a7d
	- fabric-item-groups-v0@0.2.5+351679a77d
	- fabric-key-binding-api-v1@1.0.4+9354966b7d
	- fabric-keybindings-v0@0.2.1+ca58154a7d
	- fabric-language-kotlin@1.6.1+kotlin.1.5.10
	- fabric-lifecycle-events-v1@1.2.1+ca58154a7d
	- fabric-loot-tables-v1@1.0.2+ca58154a7d
	- fabric-mining-levels-v0@0.1.3+ca58154a7d
	- fabric-models-v0@0.2.1+ca58154a7d
	- fabric-networking-api-v1@1.0.3+e3c9d0627d
	- fabric-networking-blockentity-v0@0.2.8+ca58154a7d
	- fabric-networking-v0@0.3.2+ca58154a7d
	- fabric-object-builder-api-v1@1.9.4+9354966b7d
	- fabric-object-builders-v0@0.7.2+ca58154a7d
	- fabric-particles-v1@0.2.4+ca58154a7d
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.4+ca58154a7d
	- fabric-renderer-api-v1@0.4.1+ca58154a7d
	- fabric-renderer-indigo@0.4.4+ca58154a7d
	- fabric-renderer-registries-v1@2.2.1+ca58154a7d
	- fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d
	- fabric-rendering-fluids-v1@0.1.13+ca58154a7d
	- fabric-rendering-v0@1.1.2+ca58154a7d
	- fabric-rendering-v1@1.5.1+ca58154a7d
	- fabric-resource-loader-v0@0.4.2+ca58154a7d
	- fabric-screen-api-v1@1.0.0+c045166c7d
	- fabric-screen-handler-api-v1@1.1.5+9354966b7d
	- fabric-structure-api-v1@1.1.4+ca58154a7d
	- fabric-tag-extensions-v0@1.1.1+ca58154a7d
	- fabric-textures-v0@1.0.6+ca58154a7d
	- fabric-tool-attribute-api-v1@1.2.6+ca58154a7d
	- fabricloader@0.11.6
	- fallflyinglib@1.1.0
	- fdlink@0.9.4
	- fdlink_1_12_2@0.9.4
	- fdlink_1_15_2@0.9.4
	- fdlink_1_16@0.9.4
	- fdlink_1_7_10@0.9.4
	- fdlink_1_8_9@0.9.4
	- fdlink_api@0.1.0
	- fdlink_common@0.9.4
	- fiber@0.23.0-2
	- flan@1.16.5-1.6.2
	- grindenchantments@1.1.3+1.16.3
	- illuminations@1.5.1
	- invview@1.4.1-1.16.4+
	- jankson@3.0.1+j1.2.0
	- java@11
	- libgui@3.3.5+1.16.5
	- lithium@0.6.6
	- mermod@1.3
	- minecraft@1.16.5
	- moborigins@1.4.0
	- modmenu@1.16.22
	- net_dv8tion_jda@4.2.1_266
	- net_sf_trove4j_trove4j@3.0.3
	- netherportalspread-fabric@5.4
	- observable@0.1.3
	- org_apache_commons_commons-collections4@4.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.10
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
	- org_json_json@20210307
	- org_slf4j_slf4j-api@1.7.25
	- org_slf4j_slf4j-nop@1.7.25
	- origins@0.7.0
	- origins-classes@1.1.1
	- pehkui@2.1.0+21w18a
	- phosphor@0.7.2+build.12
	- reach-entity-attributes@1.0.1
	- repurposed_structures@1.16.5-1.9.0
	- roughlyenoughitems@5.12.248
	- roughlyenoughitems-api@5.12.248
	- roughlyenoughitems-default-plugin@5.12.248
	- roughlyenoughitems-runtime@5.12.248
	- rpgstats@4.0.5+1.16.5
	- seasons@1.2-BETA
	- slimeorigin@3.0.0
	- terraform-biome-builder-api-v1@1.0.4
	- terraform-config-api-v1@1.0.3
	- terraform-dirt-api-v1@1.1.3
	- terraform-overworld-biome-extensions-api-v1@1.0.3
	- terraform-shapes-api-v1@1.0.3
	- terraform-surfaces-api-v1@1.0.3
	- terraform-tree-api-v1@1.0.4
	- terraform-wood-api-v1@1.0.3
	- terrestria@2.2.0
	- things@0.1.4
	- traverse@3.3.3
	- voyager@1.0.0
	- worldedit@7.2.5+57d5ac9
	- worldeditcui@1.16.5+02
[21:45:45] [main/WARN]: Mod `net_dv8tion_jda` (4.2.1_266) does not respect SemVer - comparison support is limited.
[21:45:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/minecraft/multicraft/servers/server1042233/jar/fabric_1.16.5.jar Service=Knot/Fabric Env=SERVER
[21:45:46] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 0 override(s) found
[21:45:46] [main/WARN]: Error loading class: net/minecraft/class_746 (java.lang.ClassNotFoundException: net/minecraft/class_746)
[21:45:46] [main/WARN]: @Mixin target net.minecraft.class_746 was not found architectury.mixins.json:PlayerAttackInvoker
[21:45:46] [main/WARN]: Error loading class: net/minecraft/class_745 (java.lang.ClassNotFoundException: net/minecraft/class_745)
[21:45:46] [main/WARN]: @Mixin target net.minecraft.class_745 was not found architectury.mixins.json:PlayerAttackInvoker
[21:45:46] [main/WARN]: Error loading class: info/tehnut/harvest/Harvest (java.lang.ClassNotFoundException: info/tehnut/harvest/Harvest)
[21:45:46] [main/WARN]: Error loading class: wraith/harvest_scythes/ScytheTool (java.lang.ClassNotFoundException: wraith/harvest_scythes/ScytheTool)
[21:45:46] [main/WARN]: Error loading class: net/minecraft/class_465 (java.lang.ClassNotFoundException: net/minecraft/class_465)
[21:45:46] [main/WARN]: @Mixin target net.minecraft.class_465 was not found curios.mixins.json:HandledScreenMixin
[21:45:46] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[21:45:46] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)
[21:45:52] [main/INFO]: [STDOUT]: RPGStats loaded!
[21:45:52] [main/INFO]: [STDOUT]: Loading Collective (Fabric).
[21:45:52] [main/INFO]: Mod Initialized!
[21:45:52] [main/INFO]: [STDOUT]: -Initialized Enderitemod!-
[21:45:52] [main/INFO]: Origins 0.7.0 is initializing. Have fun!
[21:45:52] [main/INFO]: WorldEdit for Fabric (version 7.2.5+57d5ac9) is loaded
[21:45:52] [main/INFO]: Setting up a new Charm-based module 'charm'
[21:45:53] [main/INFO]: Initialising module Acquisition
[21:45:53] [main/INFO]: Initialising module AerialAffinity
[21:45:53] [main/INFO]: Initialising module AnvilImprovements
[21:45:53] [main/INFO]: Initialising module ArmorInvisibility
[21:45:53] [main/INFO]: Initialising module Atlas
[21:45:53] [main/INFO]: Initialising module AutoRestock
[21:45:53] [main/INFO]: Initialising module AutomaticRecipeUnlock
[21:45:53] [main/INFO]: Initialising module BatBuckets
[21:45:53] [main/INFO]: Initialising module BeaconsHealMobs
[21:45:53] [main/INFO]: Initialising module Beekeepers
[21:45:53] [main/INFO]: Initialising module BlockOfEnderPearls
[21:45:53] [main/INFO]: Initialising module BlockOfGunpowder
[21:45:53] [main/INFO]: Initialising module BlockOfSugar
[21:45:53] [main/INFO]: Initialising module Bookcases
[21:45:53] [main/INFO]: Initialising module CampfiresNoDamage
[21:45:53] [main/INFO]: Initialising module Candles
[21:45:53] [main/INFO]: Initialising module CaveSpidersDropCobwebs
[21:45:53] [main/INFO]: Initialising module ChickensDropFeathers
[21:45:53] [main/INFO]: Initialising module CoralSeaLanterns
[21:45:53] [main/INFO]: Initialising module CoralSquids
[21:45:53] [main/INFO]: Initialising module Core
[21:45:53] [main/INFO]: Initialising module Crates
[21:45:53] [main/INFO]: Initialising module DecreaseRepairCost
[21:45:53] [main/INFO]: Initialising module DirtToPath
[21:45:53] [main/INFO]: Initialising module EndermitePowder
[21:45:53] [main/INFO]: Initialising module EntitySpawners
[21:45:53] [main/INFO]: Initialising module ExtendNetherite
[21:45:53] [main/INFO]: Initialising module ExtraRecipes
[21:45:53] [main/INFO]: Initialising module FeatherFallingCrops
[21:45:53] [main/INFO]: Initialising module Glowballs
[21:45:53] [main/INFO]: Initialising module GoldBars
[21:45:53] [main/INFO]: Initialising module GoldChains
[21:45:53] [main/INFO]: Initialising module GoldLanterns
[21:45:53] [main/INFO]: Initialising module HoeHarvesting
[21:45:53] [main/INFO]: Initialising module HuskImprovements
[21:45:53] [main/INFO]: Initialising module InventoryTidying
[21:45:53] [main/INFO]: Initialising module Kilns
[21:45:53] [main/INFO]: Initialising module Lumberjacks
[21:45:53] [main/INFO]: Initialising module MapTooltips
[21:45:53] [main/INFO]: Initialising module MineshaftImprovements
[21:45:53] [main/INFO]: Initialising module Mooblooms
[21:45:53] [main/INFO]: Initialising module MorePortalFrames
[21:45:53] [main/INFO]: Initialising module MoreVillageBiomes
[21:45:53] [main/INFO]: Initialising module MusicImprovements
[21:45:53] [main/INFO]: Initialising module NetheriteNuggets
[21:45:53] [main/INFO]: Initialising module ParrotsStayOnShoulder
[21:45:53] [main/INFO]: Initialising module PathToDirt
[21:45:53] [main/INFO]: Initialising module PlayerPressurePlates
[21:45:53] [main/INFO]: Initialising module PlayerState
[21:45:53] [main/INFO]: Initialising module PortableCrafting
[21:45:53] [main/INFO]: Initialising module PortableEnderChest
[21:45:53] [main/INFO]: Initialising module RaidHorns
[21:45:53] [main/INFO]: Initialising module RedstoneLanterns
[21:45:53] [main/INFO]: Initialising module RedstoneSand
[21:45:53] [main/INFO]: Initialising module RefinedObsidian
[21:45:53] [main/INFO]: Initialising module RemoveNitwits
[21:45:53] [main/INFO]: Initialising module RemovePotionGlint
[21:45:53] [main/INFO]: Initialising module ShulkerBoxTooltips
[21:45:53] [main/INFO]: Initialising module SleepImprovements
[21:45:53] [main/INFO]: Initialising module SmoothGlowstone
[21:45:53] [main/INFO]: Initialising module SnowStorms
[21:45:53] [main/INFO]: Initialising module StackableEnchantedBooks
[21:45:53] [main/INFO]: Initialising module StackablePotions
[21:45:53] [main/INFO]: Initialising module StackableStews
[21:45:53] [main/INFO]: Initialising module StrayImprovements
[21:45:53] [main/INFO]: Initialising module TamedAnimalsNoDamage
[21:45:53] [main/INFO]: Initialising module Tinted
[21:45:53] [main/INFO]: Initialising module UseTotemFromInventory
[21:45:53] [main/INFO]: Initialising module VariantBarrels
[21:45:53] [main/INFO]: Initialising module VariantBookshelves
[21:45:53] [main/INFO]: Initialising module VariantChests
[21:45:53] [main/INFO]: Initialising module VariantLadders
[21:45:53] [main/INFO]: Initialising module VariantMobTextures
[21:45:53] [main/INFO]: Initialising module VillagersFollowEmeraldBlocks
[21:45:53] [main/INFO]: Initialising module WanderingTraderImprovements
[21:45:53] [main/INFO]: Initialising module WitchesDropLuck
[21:45:53] [main/INFO]: Initialising module Woodcutters
[21:45:53] [main/INFO]: Done setting up 'charm'
[21:45:53] [main/INFO]: Registering class observable.net.BetterChannel$PartialPacketBegin
[21:45:54] [main/INFO]: Registered class observable.net.BetterChannel$PartialPacketBegin
[21:45:54] [main/INFO]: Registering class observable.net.BetterChannel$PartialPacketData
[21:45:54] [main/INFO]: Registered class observable.net.BetterChannel$PartialPacketData
[21:45:54] [main/INFO]: Registering class observable.net.C2SPacket$InitTPSProfile
[21:45:54] [main/INFO]: Registered class observable.net.C2SPacket$InitTPSProfile
[21:45:54] [main/INFO]: Registering class observable.net.C2SPacket$RequestTeleport
[21:45:54] [main/INFO]: Registered class observable.net.C2SPacket$RequestTeleport
[21:45:54] [main/INFO]: Registering class observable.net.C2SPacket$RequestAvailability
[21:45:54] [main/INFO]: Registered class observable.net.C2SPacket$RequestAvailability
[21:45:54] [main/INFO]: Registering class observable.net.S2CPacket$ProfilingStarted
[21:45:54] [main/INFO]: Registered class observable.net.S2CPacket$ProfilingStarted
[21:45:54] [main/INFO]: Registering class observable.net.S2CPacket$ProfilingCompleted
[21:45:54] [main/INFO]: Registered class observable.net.S2CPacket$ProfilingCompleted
[21:45:54] [main/INFO]: Registering class observable.net.S2CPacket$ProfilingResult
[21:45:54] [main/INFO]: Registered class observable.net.S2CPacket$ProfilingResult
[21:45:54] [main/INFO]: Registering class observable.net.S2CPacket$Availability
[21:45:54] [main/INFO]: Registered class observable.net.S2CPacket$Availability
[21:45:55] [main/INFO]: Trying to read config file...
[21:45:55] [main/INFO]: A config file was found, loading it..
[21:45:55] [main/INFO]: Successfully loaded config file.
[21:45:55] [main/INFO]: [Dynmap] Mod Support API available
[21:45:55] [main/INFO]: Starting provider: Item Tags
[21:45:55] [main/INFO]: Item Tags finished after 0 ms
[21:45:55] [main/INFO]: All providers took: 1 ms
[21:45:55] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'netherportalspread-fabric'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric_1.16.5.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric_1.16.5.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric_1.16.5.jar:?]
	at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric_1.16.5.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric_1.16.5.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric_1.16.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric_1.16.5.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric_1.16.5.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric_1.16.5.jar:?]
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.class_2348.method_10250(net.minecraft.class_2960)'
	at com.natamus.netherportalspread.util.Util.loadSpreadBlocks(Util.java:70) ~[netherportalspread-fabric_1.16.x-5.4.jar:?]
	at com.natamus.netherportalspread.util.Util.loadSpreadBlocks(Util.java:137) ~[netherportalspread-fabric_1.16.x-5.4.jar:?]
	at com.natamus.netherportalspread.Main.registerEvents(Main.java:35) ~[netherportalspread-fabric_1.16.x-5.4.jar:?]
	at com.natamus.netherportalspread.Main.onInitialize(Main.java:28) ~[netherportalspread-fabric_1.16.x-5.4.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric_1.16.5.jar:?]
	... 17 more

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the bug report! This has been fixed in version 5.5 of the mod.

https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread-fabric/files/all
