### ISSUE TITLE
Game still crash when breaking head.

### ISSUE THREAD

**Issue by Mirarara** [ricksouth/serilum-mc-mods#791]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.9
Environment: Singleplayer / Multiplayer

Mod name: Just Mob Heads
Mod version: justmobheads_1.16.5-5.1

## **Description**
The game crash when breaking a head. Removing the mod solved the issue.

## **Crash report**
`[21Nov2021 01:28:38.487] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: 'com.mojang.authlib.GameProfile net.minecraft.tileentity.SkullTileEntity.func_152108_a()'
	Index: 18
	Listeners:
		0: HIGHEST
		1: ASM: class me.desht.pneumaticcraft.common.tileentity.TileEntitySecurityStation$Listener onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		2: ASM: wayoftime.bloodmagic.util.handler.event.GenericHandler@102a4017 onBreakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		3: HIGH
		4: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		5: NORMAL
		6: net.minecraftforge.eventbus.EventBus$$Lambda$2682/0x0000000840b36040@32979b46
		7: ASM: class net.blay09.mods.kleeslabs.BlockBreakHandler onBreakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		8: net.minecraftforge.eventbus.EventBus$$Lambda$2682/0x0000000840b36040@556b6513
		9: ASM: class com.direwolf20.buildinggadgets.common.events.BreakEventHandler GetDrops(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		10: ASM: class owmii.losttrinkets.handler.EventHandler onBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		11: ASM: class cofh.ensorcellation.event.CommonEvents handleBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		12: ASM: com.lothrazar.cyclic.enchant.EnchantXp@224c7a74 handleBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		13: ASM: stepsword.mahoutsukai.handlers.ServerHandler@32b7b2ff breakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		14: net.minecraftforge.eventbus.EventBus$$Lambda$2682/0x0000000840b36040@42fa2be
		15: net.minecraftforge.eventbus.EventBus$$Lambda$2682/0x0000000840b36040@6c8e40f1
		16: ASM: vazkii.quark.content.tweaks.module.HoeHarvestingModule@1ad94135 onBlockBroken(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		17: ASM: com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeListener@2ac8b8ce onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		18: ASM: com.natamus.justmobheads.events.HeadDropEvent@347d018f onPlayerHeadBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		19: LOW
		20: ASM: class cofh.core.event.AreaEffectEvents handleBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		21: LOWEST
		22: ASM: com.lothrazar.cyclic.enchant.EnchantExcavation@5028eb61 onBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		23: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem consumeDurabilityOnBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		24: ASM: class com.simibubi.create.content.curiosities.symmetry.SymmetryHandler onBlockDestroyed(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		25: net.minecraftforge.eventbus.EventBus$$Lambda$2682/0x0000000840b36040@62cdbb8d
		26: net.minecraftforge.eventbus.EventBus$$Lambda$2682/0x0000000840b36040@6c00193a
		27: ASM: blusunrize.immersiveengineering.common.EventHandler@216256de breakLast(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
		28: net.minecraftforge.eventbus.EventBus$$Lambda$2682/0x0000000840b36040@15c37c56
java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.tileentity.SkullTileEntity.func_152108_a()'
	at com.natamus.justmobheads.events.HeadDropEvent.onPlayerHeadBreak(HeadDropEvent.java:156)
	at net.minecraftforge.eventbus.ASMEventHandler_1474_HeadDropEvent_onPlayerHeadBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:602)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:230)
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220)
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40)
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:829)

[21Nov2021 01:28:38.490] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.tileentity.SkullTileEntity.func_152108_a()'
	at com.natamus.justmobheads.events.HeadDropEvent.onPlayerHeadBreak(HeadDropEvent.java:156) ~[justmobheads:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_1474_HeadDropEvent_onPlayerHeadBreak_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:602) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:230) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod. Seems like the 1.16.5 had a clientonly method which was changed in 1.17. Anyways, should work now!

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files
