### ISSUE TITLE
Teleport crashing with new Collective 3.7

### ISSUE THREAD

**Issue by GhostRiderGrey** [ricksouth/serilum-mc-mods#796]
## **Information**
Minecraft version: 1.17.1
Modloader:  Fabric
Fabric loader version: 1.12.5
Environment: Singleplayer / Multiplayer  Yes!

Mod name: Collective (or possibly Starter Kit)
Mod version:  collective-fabric-1.17.x-3.7

## **Description**
Morning Serilum. Updated this morning on my server to the current version of Collective (3.7) and Starter Kit, and now when I'm using the teleport function of Xaeros World Map I get the crash shown below and it kicks me back to the server list. Reverting to collective-fabric-1.17.x-3.0 solves the problem.  Full server log included.  Thanks!

## **Crash report**
[10:54:51] [Server thread/ERROR]: Command exception: /tp @s -409 66.5 -215
java.lang.NullPointerException: Cannot invoke "java.lang.Object.toString()" because "command" is null
        at com.natamus.starterkit.events.FirstSpawnEvent.onCommand(FirstSpawnEvent.java:41) ~[starterkit-fabric_1.17.x-3.0.jar:?]
        at com.natamus.starterkit.Main.lambda$registerEvents$2(Main.java:43) ~[starterkit-fabric_1.17.x-3.0.jar:?]
        at com.natamus.starterkit.Main$$Lambda$5867/0x000000006d511250.onCommandParse(Unknown Source) ~[?:?]
        at com.natamus.collective_fabric.fabric.callbacks.CollectiveCommandEvents.lambda$static$0(CollectiveCommandEvents.java:14) ~[collective-fabric-1.17.x-3.7.jar:?]
        at com.natamus.collective_fabric.fabric.callbacks.CollectiveCommandEvents$$Lambda$5866/0x000000006d511030.onCommandParse(Unknown Source) ~[?:?]
        at net.minecraft.class_2170.handler$zna000$Commands_performCommand(class_2170.java:3026) [intermediary-server.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:251) [intermediary-server.jar:?]
        at net.minecraft.class_3244.method_14370(class_3244.java:1222) [intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31286(class_3244.java:1206) [intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12048(class_3244.java:1189) [intermediary-server.jar:?]
        at net.minecraft.class_2797.method_12115(class_2797.java:30) [intermediary-server.jar:?]
        at net.minecraft.class_2797.method_11054(class_2797.java:7) [intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) [intermediary-server.jar:?]
        at net.minecraft.class_2600$$Lambda$9487/0x0000000076141820.run(Unknown Source) [intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer$$Lambda$8040/0x0000000074f24c30.run(Unknown Source) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:883) [?:?]

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7614070/latest.log)

**Comment by ricksouth** [comment]
Thanks Grey! Should be fixed in version 3.1 of Starter Kit. But please let me know if the issue persists.

https://www.curseforge.com/minecraft/mc-mods/starter-kit-fabric/files/all
