### ISSUE TITLE
Collective is crashing the game: The game crashed whilst initializing game Error: java.lang.NullPointerException: Initializing game Exit Code: -1

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#798]

**Comment by ghost** [comment]
i have optifine but i know it isnt a compatibility issue because i removed optifine and it did nothing to change the issue. crash report: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 11/29/21 2:36 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at mod.lucky.init.Register.registerRecipes(Register.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_Register_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mod.lucky.init.Register.registerRecipes(Register.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_Register_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 588660528 bytes (561 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G6_pre1 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version        | Source                                  | Signature                                |
	|:----- |:------------- |:-------------- |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft     | 1.12.2         | minecraft.jar                           | None                                     |
	| LCH   | mcp           | 9.42           | minecraft.jar                           | None                                     |
	| LCH   | FML           | 8.0.99.99      | forge-1.12.2-14.23.5.2855.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge         | 14.23.5.2855   | forge-1.12.2-14.23.5.2855.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | foamfixcore   | 7.7.4          | minecraft.jar                           | None                                     |
	| LCH   | jei           | 4.16.1.301     | jei_1.12.2-4.16.1.301.jar               | None                                     |
	| LCH   | appleskin     | 1.0.14         | AppleSkin-mc1.12-1.0.14.jar             | None                                     |
	| LCH   | quark         | r1.6-179       | Quark-r1.6-179.jar                      | None                                     |
	| LCH   | autoreglib    | 1.3-32         | AutoRegLib-1.3-32.jar                   | None                                     |
	| LCH   | collective    | 3.0            | collective-1.12.2-3.0.jar               | None                                     |
	| LCH   | foamfix       | 0.10.14-1.12.2 | foamfix-0.10.14-1.12.2.jar              | None                                     |
	| LCH   | ftblib        | 5.4.7.2        | FTBLib-5.4.7.2.jar                      | None                                     |
	| LCH   | jeresources   | 0.9.2.60       | JustEnoughResources-1.12.2-0.9.2.60.jar | None                                     |
	| LCH   | kalstuff      | 0.8.0d         | KalStuff-1.12.2-1.0.0-beta.jar          | None                                     |
	| LCH   | lucky         | 7.6.0          | luckyblock-1.12.2-1-forge.jar           | None                                     |
	| LCH   | quarkoddities | 1              | QuarkOddities-1.12.2.jar                | None                                     |
	| LCH   | tips          | 1.0.9          | Tips-1.12.2-1.0.9.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | treeharvester | 4.0            | treeharvester_1.12.2-4.0.jar            | None                                     |
	| LCH   | waystones     | 4.1.0          | Waystones_1.12.2-4.1.0.jar              | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9664' Renderer: 'Intel(R) UHD Graphics 600'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 600 GL version 4.6.0 - Build 27.20.100.9664, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 5
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.9664
	OpenGlRenderer: Intel(R) UHD Graphics 600
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by ricksouth** [comment]
Collective isn't mentioned in the crash log. It says the error is here:
java.lang.NullPointerException: Initializing game
at mod.lucky.init.Register.registerRecipes(Register.java:54)

"luckyblock-1.12.2-1-forge.jar"

**Comment by ghost** [comment]
thats weird. if i remove collective, the game launches.

**Comment by ricksouth** [comment]
Does it work with lucky block removed? Might be a compatibility issue, though I haven't seen it before.

**Comment by ghost** [comment]
i just thought of that, im trying it right now.

**Comment by ghost** [comment]
i was wrong, it has nothing to do with collective, it just didnt crash before because i forgot to remove the mod that needed it. in conclusion, this is unrelated to your mod and im stupid.

**Comment by ricksouth** [comment]
No problem, glad you worked it out. Thanks for giving my mod a try!

**Comment by ghost** [comment]
you WERE right about there being something wrong with the lucky block mod, i removed it and it works fine now.
