### ISSUE TITLE
Collective (fabric) causes failure to start server - The requested compatibility level JAVA_17 could not be set. 

### ISSUE THREAD

**Issue by Mickey11592** [ricksouth/serilum-mc-mods#812]
## **Information**
Minecraft version: 1.18
Modloader: Forge / Fabric: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: 0.10.1
Environment: Multiplayer

Mod name: Collective (fabric)
Mod version: collective-fabric-1.18.x-3.9.jar

## **Description**
Server was starting fine until I tried to add the Replanting Crops mod (https://www.curseforge.com/minecraft/mc-mods/replanting-crops-fabric).  This required the Collective mod so I added this.
The Collective mod is causing the server to fail to start with the error below.
I do have the server running using java 17 
java 16 fails when trying to start the server with the following:
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

## **Crash report**
14:55:19
SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/amp/.ampdata/instances/Minecraft-Newest/Minecraft/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
Compatibility level set to JAVA_16
Console14:55:19
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:62)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:100)
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:74)
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)
... 1 more
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)
... 2 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config collective_fabric.mixins.json
at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:87)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
... 7 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
... 13 more

If there's any more information I can provide (or any troubleshooting steps that I can do to help) please let me know.

**Comment by ricksouth** [comment]
Please update the Fabric Loader to 0.12.6 or above. It's probably 0.12.5

**Comment by ricksouth** [comment]
https://fabricmc.net/use/

**Comment by Mickey11592** [comment]
That fixed it, thank you very much!  I thought I had the newest version since I installed it just a few days ago, but apparently I didn't.  My apologies.

**Comment by ricksouth** [comment]
No problem! Thanks for giving the mod a try :)
