### ISSUE TITLE
3.12 Unable to create new world

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#815]
## **Information**
Minecraft version: 1.18
Modloader: Fabric
Fabric loader version: 0.12.8
Fabric API: 0.44.0
Environment: Singleplayer

Mod name: Collective (Fabric)
Mod version: 3.12

## **Description**

Cannot create new world with 3.12, rolled back to 3.11 and it works fine.

Errors in currently selected datapacks prevented the world from loading.

## **Crash report**
```
[12:34:08] [Render thread/ERROR]: Mixin apply for mod collective-fabric failed collective_fabric.mixins.json:CommandsMixin -> net.minecraft.class_2170: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on Commands_performCommand could not find any targets matching 'performCommand(Lnet/minecraft/commands/CommandSourceStack;Ljava/lang/String;)I' in net.minecraft.class_2170. Using refmap collective-fabric-1.18.x-refmap.json [PREINJECT Applicator Phase -> collective_fabric.mixins.json:CommandsMixin -> Prepare Injections ->  -> handler$zbe000$Commands_performCommand(Lnet/minecraft/class_2168;Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/mojang/brigadier/StringReader;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on Commands_performCommand could not find any targets matching 'performCommand(Lnet/minecraft/commands/CommandSourceStack;Ljava/lang/String;)I' in net.minecraft.class_2170. Using refmap collective-fabric-1.18.x-refmap.json [PREINJECT Applicator Phase -> collective_fabric.mixins.json:CommandsMixin -> Prepare Injections ->  -> handler$zbe000$Commands_performCommand(Lnet/minecraft/class_2168;Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/mojang/brigadier/StringReader;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at jdk.internal.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5350.<init>(class_5350.java:39) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:88) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:2152) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:2003) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_29607(class_310.java:1947) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:278) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:214) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:40) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:121) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:491) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[intermediary-minecraft-1.18-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:200) [intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1142) [intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [intermediary-minecraft-1.18-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[12:34:08] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2170 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5350.<init>(class_5350.java:39) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:88) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:2152) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:2003) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_29607(class_310.java:1947) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:278) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:214) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:40) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:121) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:491) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[intermediary-minecraft-1.18-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:200) [intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1142) [intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [intermediary-minecraft-1.18-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	... 43 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [collective_fabric.mixins.json:CommandsMixin] from phase [DEFAULT] in config [collective_fabric.mixins.json] from mod [collective-fabric] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	... 43 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on Commands_performCommand could not find any targets matching 'performCommand(Lnet/minecraft/commands/CommandSourceStack;Ljava/lang/String;)I' in net.minecraft.class_2170. Using refmap collective-fabric-1.18.x-refmap.json [PREINJECT Applicator Phase -> collective_fabric.mixins.json:CommandsMixin -> Prepare Injections ->  -> handler$zbe000$Commands_performCommand(Lnet/minecraft/class_2168;Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/mojang/brigadier/StringReader;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at jdk.internal.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	... 43 more
[12:36:23] [pool-3-thread-2/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connection reset
	at net.minecraft.class_4341.method_20998(class_4341.java:436) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:325) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:320) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4360.method_33413(class_4360.java:216) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_5784.run(class_5784.java:32) [intermediary-minecraft-1.18-client.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[12:37:21] [pool-3-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connect timed out
	at net.minecraft.class_4341.method_20998(class_4341.java:436) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:325) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:320) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_4360.method_33413(class_4360.java:216) ~[intermediary-minecraft-1.18-client.jar:?]
	at net.minecraft.class_5784.run(class_5784.java:32) [intermediary-minecraft-1.18-client.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[12:37:56] [Render thread/INFO]: Stopping!
```

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I've fixed it in version 3.13 of Collective.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all
