### ISSUE TITLE
Server Crash with infinitetrading-fabric_1.18.x-2.0

### ISSUE THREAD

**Issue by pelletstove** [ricksouth/serilum-mc-mods#825]
## **Information**
Minecraft version: 1.18
Modloader: Fabric
Fabric loader version: 0.12.8
Environment: Multiplayer

Mod name: infinitetrading-fabric_1.18.x-2.0

## **Description**
Server Crash

## **Crash report**
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 12/5/21, 8:01 PM
Description: Saving entity NBT

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1914 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3853$class_4165.method_7246(class_3853.java:696)
	at net.minecraft.class_3988.method_19170(class_3988.java:251)
	at net.minecraft.class_3989.method_7237(class_3989.java:127)
	at net.minecraft.class_3988.method_8264(class_3988.java:115)
	at net.minecraft.class_3988.method_5652(class_3988.java:172)
	at net.minecraft.class_3989.method_5652(class_3989.java:139)
	at net.minecraft.class_1297.method_5647(class_1297.java:1653)
	at net.minecraft.class_1297.method_5786(class_1297.java:1589)
	at net.minecraft.class_1297.method_5662(class_1297.java:1597)
	at net.minecraft.class_5565.method_31734(class_5565.java:109)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5565.method_31760(class_5565.java:107)
	at net.minecraft.class_5579.method_31812(class_5579.java:293)
	at net.minecraft.class_5579.method_31846(class_5579.java:374)
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.forEach(LongOpenHashSet.java:802)
	at net.minecraft.class_5579.method_31829(class_5579.java:368)
	at net.minecraft.class_3218.method_14176(class_3218.java:751)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:561)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:585)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:848)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229)
	... 28 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [infinitetrading_fabric.mixins.json:MerchantOfferMixin] from phase [DEFAULT] in config [infinitetrading_fabric.mixins.json] from mod [infinitetrading-fabric] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 31 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on MerchantOffer could not find any targets matching '<init>(Lnet/minecraft/nbt/CompoundTag;)V' in net.minecraft.class_1914. Using refmap fabric-mod-refmap.json [PREINJECT Applicator Phase -> infinitetrading_fabric.mixins.json:MerchantOfferMixin -> Prepare Injections ->  -> handler$bfc000$MerchantOffer(Lnet/minecraft/class_2487;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3853$class_4165.method_7246(class_3853.java:696)
	at net.minecraft.class_3988.method_19170(class_3988.java:251)
	at net.minecraft.class_3989.method_7237(class_3989.java:127)
	at net.minecraft.class_3988.method_8264(class_3988.java:115)
	at net.minecraft.class_3988.method_5652(class_3988.java:172)
	at net.minecraft.class_3989.method_5652(class_3989.java:139)

-- Entity being saved --
Details:
	Entity Type: minecraft:wandering_trader (net.minecraft.class_3989)
	Entity ID: 18270
	Entity Name: Lessie
	Entity's Exact location: -37.50, 69.00, -659.50
	Entity's Block location: World: (-38,69,-660), Section: (at 10,5,12 in -3,4,-42; chunk contains blocks -48,-64,-672 to -33,319,-657), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1297.method_5647(class_1297.java:1653)
	at net.minecraft.class_1297.method_5786(class_1297.java:1589)
	at net.minecraft.class_1297.method_5662(class_1297.java:1597)
	at net.minecraft.class_5565.method_31734(class_5565.java:109)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5565.method_31760(class_5565.java:107)
	at net.minecraft.class_5579.method_31812(class_5579.java:293)
	at net.minecraft.class_5579.method_31846(class_5579.java:374)
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.forEach(LongOpenHashSet.java:802)
	at net.minecraft.class_5579.method_31829(class_5579.java:368)
	at net.minecraft.class_3218.method_14176(class_3218.java:751)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:561)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:585)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:848)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 14846589960 bytes (14158 MiB) / 17179869184 bytes (16384 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen Threadripper 3970X 32-Core Processor 
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 32
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 2080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e07
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Memory slot #4 capacity (MB): 16384.00
	Memory slot #4 clockSpeed (GHz): 2.67
	Memory slot #4 type: DDR4
	Memory slot #5 capacity (MB): 16384.00
	Memory slot #5 clockSpeed (GHz): 2.67
	Memory slot #5 type: DDR4
	Memory slot #6 capacity (MB): 16384.00
	Memory slot #6 clockSpeed (GHz): 2.67
	Memory slot #6 type: DDR4
	Memory slot #7 capacity (MB): 16384.00
	Memory slot #7 clockSpeed (GHz): 2.67
	Memory slot #7 type: DDR4
	Virtual memory max (MB): 139140.22
	Virtual memory used (MB): 53226.35
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms16384m -Xmx16384m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		anvilrestoration-fabric: Anvil Restoration (Fabric) 1.1
		architectury: Architectury 3.1.45
		balm-fabric: Balm 2.1.1+0
		bclib: BCLib 1.0.2
		betternether: Better Nether 6.0.1
		betterspawnercontrol-fabric: Better Spawner Control (Fabric) 1.5
		blue_endless_jankson: jankson 1.2.1
		bottledair-fabric: Bottled Air (Fabric) 1.0
		campfirespawnandtweaks-fabric: Campfire Spawn and Tweaks (Fabric) 1.4
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		carrier: Carrier 1.9.0
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.0.42
		collective-fabric: Collective (Fabric) 3.13
		compacthelpcommand-fabric: Compact Help Command (Fabric) 1.1
		configurablefurnaceburntime-fabric: Configurable Furnace Burn Time (Fabric) 1.0
		copperarmorandtools: Copper Armor & Tools 1.4.5
		crowdin-translate: CrowdinTranslate 1.4+1.18
		dismountentity-fabric: Dismount Entity (Fabric) 1.5
		doubledoors-fabric: Double Doors (Fabric) 3.1
		dragondropselytra-fabric: Dragon Drops Elytra (Fabric) 1.4
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18
		easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4
		easyelytratakeoff-fabric: Easy Elytra Takeoff (Fabric) 2.2
		enhancedcelestials: Enhanced Celestials 2.0.6
		extendedbonemeal-fabric: Extended Bone Meal (Fabric) 1.4
		extractpoison-fabric: Extract Poison (Fabric) 1.6
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.8
		fallingtree: FallingTree 2.15.2
		fiber: fiber 0.23.0-2
		firespreadtweaks-fabric: Fire Spread Tweaks (Fabric) 1.2
		fixedanvilrepaircost-fabric: Fixed Anvil Repair Cost (Fabric) 1.6
		furnacerecycle-fabric: Furnace Recycle (Fabric) 1.0
		gbfabrictools: GBfabrictools 1.3.4+1.18
		giantspawn-fabric: Giant Spawn (Fabric) 2.7
		grassseeds-fabric: Grass Seeds (Fabric) 1.6
		grindstonesharpertools-fabric: Grindstone Sharper Tools (Fabric) 1.6
		guiclock-fabric: GUI Clock (Fabric) 3.0
		guicompass-fabric: GUI Compass (Fabric) 1.8
		handoveryouritems-fabric: Hand Over Your Items (Fabric) 1.3
		healingcampfire-fabric: Healing Campfire (Fabric) 3.3
		hoetweaks-fabric: Hoe Tweaks (Fabric) 1.2
		huskspawn-fabric: Husk Spawn (Fabric) 1.4
		infinitetrading-fabric: Infinite Trading (Fabric) 2.0
		inventorysorter: Inventory Sorter 1.8.0-1.18
		inventorytotem-fabric: Inventory Totem (Fabric) 1.5
		iris: Iris 1.1.3
		java: Java HotSpot(TM) 64-Bit Server VM 17
		justmobheads-fabric: Just Mob Heads (Fabric) 5.2
		keepmysoiltilled-fabric: Keep My Soil Tilled (Fabric) 1.0
		kelpfertilizer-fabric: Kelp Fertilizer (Fabric) 1.8
		kyrptconfig: Kyrpt Config 1.2.3-1.18
		lambdacontrols: LambdaControls 1.7.1+1.17
		lithium: Lithium 0.7.6-rc1
		milkallthemobs-fabric: Milk All The Mobs (Fabric) 1.6
		minecraft: Minecraft 1.18
		modmenu: Mod Menu 3.0.0
		morezombievillagers-fabric: More Zombie Villagers (Fabric) 1.5
		nametagtweaks-fabric: Name Tag Tweaks (Fabric) 1.7
		omega-config: OmegaConfig 1.0.8
		omegamute-fabric: Omega Mute (Fabric) 1.9
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		paperbooks-fabric: Paper Books (Fabric) 1.4
		petnames-fabric: Pet Names (Fabric) 1.6
		randombonemealflowers-fabric: Random Bone Meal Flowers (Fabric) 1.7
		randommobeffects-fabric: Random Mob Effects (Fabric) 1.6
		recast-fabric: Recast (Fabric) 1.5
		replantingcrops-fabric: Replanting Crops (Fabric) 2.5
		repurposed_structures: Repurposed Structures 3.1.6+1.18.0
		roughlyenoughitems: Roughly Enough Items 7.0.343
		scaffoldingdropsnearby-fabric: Scaffolding Drops Nearby (Fabric) 1.5
		seedfix: Seed Fix 1.0.0
		sleepsooner-fabric: Sleep Sooner (Fabric) 2.6
		sodium: Sodium 0.4.0-alpha5+build.9
		spruceui: SpruceUI 3.2.0+1.17
		stepup: StepUp 1.18-fabric0.43.1-1.1
		strayspawn-fabric: Stray Spawn (Fabric) 1.5
		terralith: Terralith for Fabric 2.0_b0.1.8
		toms_storage: Tom's Simple Storage Mod 1.1.19
		trashslot: TrashSlot 11.0.0
		villagernames-fabric: Villager Names (Fabric) 3.5
		weakerspiderwebs-fabric: Weaker Spiderwebs (Fabric) 2.0
		wooltweaks-fabric: Wool Tweaks (Fabric) 1.4
		wthit: wthit 4.3.1
		xaeroworldmap: Xaero's World Map 1.18.6
		zombiehorsespawn-fabric: Zombie Horse Spawn (Fabric) 3.0
		zombieproofdoors-fabric: Zombie Proof Doors (Fabric) 1.4
	Server Running: true
	Player Count: 2 / 8; [class_3222['BuggaDaddy'/12877, l='ServerLevel[BiggyButt]', x=-6.82, y=5.92, z=-616.35], class_3222['BlueCrayon13'/13446, l='ServerLevel[BiggyButt]', x=78.89, y=67.00, z=-515.90]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by ricksouth** [comment]
Does this still happen with EasierVillagerTrading uninstalled?

**Comment by pelletstove** [comment]
I had to uninstall EasierVillagerTrading just to get my world to load back up. So it doesn't happen when EasierVillagerTrading is uninstalled. I think it had something to do with a wandering_trader showing up looking at the logs. But not sure.

**Comment by ricksouth** [comment]
This has been fixed in version 3.0 of Infinite Trading, it no longer uses mixins. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/infinite-trading-fabric/
