### ISSUE TITLE
Crash on 1.18 Fabric

### ISSUE THREAD

**Issue by itsdinkd** [ricksouth/serilum-mc-mods#829]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/7/21, 4:06 PM
Description: Unexpected error

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 11 path $.
	at Not Enough Crashes deobfuscated stack trace.(1.18+build.1)
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.natamus.collective_fabric.functions.JsonFunctions.JsonStringToHashMap(JsonFunctions.java:10)
	at com.natamus.villagernames.events.VillagerEvent.onVillagerInteract(VillagerEvent.java:70)
	at com.natamus.villagernames.Main.lambda$registerEvents$1(Main.java:37)
	at net.fabricmc.fabric.api.event.player.UseEntityCallback.lambda$static$0(UseEntityCallback.java:44)
	at net.minecraft.client.network.ClientPlayerInteractionManager.handler$dje000$interactEntityAtLocation(ClientPlayerInteractionManager:3220)
	at net.minecraft.client.network.ClientPlayerInteractionManager.interactEntityAtLocation(ClientPlayerInteractionManager:400)
	at net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient:1632)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:1901)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1729)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1086)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 11 path $.
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:405)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:393)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.natamus.collective_fabric.functions.JsonFunctions.JsonStringToHashMap(JsonFunctions.java:10)
	at com.natamus.villagernames.events.VillagerEvent.onVillagerInteract(VillagerEvent.java:70)
	at com.natamus.villagernames.Main.lambda$registerEvents$1(Main.java:37)
	at net.fabricmc.fabric.api.event.player.UseEntityCallback.lambda$static$0(UseEntityCallback.java:44)
	at net.minecraft.class_636.handler$dje000$interactEntityAtLocation(class_636.java:3220)
	at net.minecraft.class_636.method_2917(class_636.java:400)
	at net.minecraft.class_310.method_1583(class_310.java:1632)
	at net.minecraft.class_310.method_1508(class_310.java:1901)

-- Affected level --
Details:
	All players: 1 total; [class_746['MrTyroneBiggums'/28261, l='ClientLevel', x=-484.46, y=64.00, z=55.59]]
	Chunk stats: 1024, 549
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,66,32), Section: (at 0,2,0 in 3,4,2; chunk contains blocks 48,-64,32 to 63,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1795411 game time, 1835958 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.1 of Villager Names.

https://www.curseforge.com/minecraft/mc-mods/villager-names

**Comment by itsdinkd** [comment]
Oh I definitely am not using this mod anymore, lol. You're about 10 months late xD
