### ISSUE TITLE
Error on attempting to look up Fabric version of mods using https://minecraft.natamus.com/

### ISSUE THREAD

**Issue by James103** [ricksouth/serilum-mc-mods#926]
## **Information**
Mods affected: Any with Forge and Fabric versions
Only affects https://minecraft.natamus.com/

## **Description**
When looking up the Fabric version of the mod on minecraft.natamus.com, an error occurs. The full stack trace is attached below.

To reproduce:
1. Open https://minecraft.natamus.com/
2. Click on any mod image that has both Forge and Fabric versions.
3. Click on the text "This mod is for Forge. For the Fabric version click here."
4. The description becomes blank and an error occurs.
5. This state can be recovered from by clicking "Next mod", "Previous mod", or "Back to overview".

## **Error**
```
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at loadSingular (script.js:562:17)
    at HTMLAnchorElement.<anonymous> (script.js:705:3)
    at HTMLDocument.dispatch (jquery-3.4.1.min.js:2:42571)
    at HTMLDocument.v.handle (jquery-3.4.1.min.js:2:40572)
```

**Comment by James103** [comment]
Closing as the redesign does not have this problem.
