### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by spyvingen** [ricksouth/serilum-mc-mods#955]
I get this error in the logs and then the server just restarts.

Some times i can play for 5-10 minutes and some times it restarts when logging in :

`[03:18:17] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:883) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2856) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_3989 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_3989 and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3f2a3a5)
        at net.minecraft.class_1799.handler$zjd000$finishUsingItem(class_1799.java:1141) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.method_7910(class_1799.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6040(class_1309.java:3079) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_37119(class_1309.java:2959) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6076(class_1309.java:2946) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2312) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_5773(class_1308.java:345) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18762(class_3218.java:699) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18472(class_1937.java:487) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_31420(class_3218.java:360) ~[server-intermediary.jar:?]
        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:328) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.redirect$zig000$fixUpdateSuppressionCrashTick(MinecraftServer.java:3750) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
        ... 6 more
[03:18:17] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-02-24_03.18.17-server.txt`

When uninstalling this mod and infinitVillagerTrades the server works fine.
Any idea of what this could be?

**Comment by James103** [comment]
1. Can you please upload `/home/container/./crash-reports/crash-2022-02-24_03.18.17-server.txt`?

**Comment by ricksouth** [comment]
Yes, could you upload the crash log @James103 mentioned?

**Comment by ricksouth** [comment]
From what I can understand out of the information given, this has been fixed in Collective version 4.9.
